package detectors

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDefaultRegistryFindsGitHubToken(t *testing.T) {
	input := []byte("token := \"ghp_abcdefghijklmnopqrstuvwxyz0123456789\"")
	var found bool
	for _, d := range DefaultRegistry() {
		for _, c := range d.Detect(input) {
			if c.DetectorID == "github-token" {
				found = true
				if c.Secret != "ghp_abcdefghijklmnopqrstuvwxyz0123456789" {
					t.Fatalf("unexpected secret: %q", c.Secret)
				}
			}
		}
	}
	if !found {
		t.Fatal("expected github-token finding")
	}
}

func TestDefaultRegistryFindsExpandedParityTokens(t *testing.T) {
	cases := []struct {
		id     string
		input  string
		secret string
	}{
		{"azure-devops-pat", strings.Repeat("a", 75) + "AZDO" + strings.Repeat("b", 5), strings.Repeat("a", 75) + "AZDO" + strings.Repeat("b", 5)},
		{"terraform-cloud-token", strings.Repeat("a", 14) + ".atlasv1." + strings.Repeat("A", 67), strings.Repeat("a", 14) + ".atlasv1." + strings.Repeat("A", 67)},
		{"netlify-token", "nfp_" + strings.Repeat("A", 40), "nfp_" + strings.Repeat("A", 40)},
		{"pulumi-token", "pul-" + strings.Repeat("a", 40), "pul-" + strings.Repeat("a", 40)},
		{"doppler-token", "dp.st." + strings.Repeat("A", 40), "dp.st." + strings.Repeat("A", 40)},
		{"tailscale-key", "tskey-api-" + strings.Repeat("A", 32), "tskey-api-" + strings.Repeat("A", 32)},
		{"ngrok-token", "ngrok_api_" + strings.Repeat("A", 32), "ngrok_api_" + strings.Repeat("A", 32)},
		{"buildkite-token", "bkua_" + strings.Repeat("a", 40), "bkua_" + strings.Repeat("a", 40)},
		{"nuget-api-key", "oy2" + strings.Repeat("a", 43), "oy2" + strings.Repeat("a", 43)},
		{"rubygems-api-key", "rubygems_" + strings.Repeat("a", 48), "rubygems_" + strings.Repeat("a", 48)},
		{"slack-webhook", "https://hooks.slack.com/services/T12345678/B12345678/abcdefghijklmnopqrstuvw", "https://hooks.slack.com/services/T12345678/B12345678/abcdefghijklmnopqrstuvw"},
		{"discord-webhook", "https://discord.com/api/webhooks/123456789012345678/" + strings.Repeat("A", 68), "https://discord.com/api/webhooks/123456789012345678/" + strings.Repeat("A", 68)},
		{"microsoft-teams-webhook", "https://example.webhook.office.com/webhookb2/11111111-2222-3333-4444-555555555555@aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/IncomingWebhook/0123456789abcdef0123456789abcdef/99999999-8888-7777-6666-555555555555", "https://example.webhook.office.com/webhookb2/11111111-2222-3333-4444-555555555555@aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/IncomingWebhook/0123456789abcdef0123456789abcdef/99999999-8888-7777-6666-555555555555"},
		{"grafana-token", "glc_eyJ" + strings.Repeat("A", 80), "glc_eyJ" + strings.Repeat("A", 80)},
		{"grafana-service-account-token", "glsa_" + strings.Repeat("A", 41), "glsa_" + strings.Repeat("A", 41)},
		{"sentry-user-token", "sntryu_" + strings.Repeat("a", 64), "sntryu_" + strings.Repeat("a", 64)},
		{"sentry-org-token", "sntrys_eyJ" + strings.Repeat("A", 197), "sntrys_eyJ" + strings.Repeat("A", 197)},
		{"honeycomb-api-key", "HONEYCOMB_API_KEY=" + strings.Repeat("a", 32), strings.Repeat("a", 32)},
		{"opsgenie-api-key", "OPSGENIE_API_KEY=123e4567-e89b-12d3-a456-426614174000", "123e4567-e89b-12d3-a456-426614174000"},
		{"splunk-observability-token", "X-Sf-Token: AbCdEfGhIjKlMnOpQrSt12", "AbCdEfGhIjKlMnOpQrSt12"},
		{"webex-bot-token", "webex " + strings.Repeat("A", 64) + "_AB12_12345678-1234-1234-1234-123456789abc", strings.Repeat("A", 64) + "_AB12_12345678-1234-1234-1234-123456789abc"},
		{"huggingface-token", "hf_" + strings.Repeat("A", 34), "hf_" + strings.Repeat("A", 34)},
		{"groq-api-key", "gsk_" + strings.Repeat("A", 52), "gsk_" + strings.Repeat("A", 52)},
		{"replicate-token", "r8_" + strings.Repeat("A", 40), "r8_" + strings.Repeat("A", 40)},
		{"airtable-pat", "patAbC123dEf4567X." + strings.Repeat("a", 64), "patAbC123dEf4567X." + strings.Repeat("a", 64)},
		{"asana-pat", "asana 123/1234567890123456/9876543210987654:abcdefghijklmnopqrstuvwxyzABCDEF123456", "123/1234567890123456/9876543210987654:abcdefghijklmnopqrstuvwxyzABCDEF123456"},
		{"clickup-token", "pk_1234567_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456", "pk_1234567_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456"},
		{"typeform-token", "tfp_" + strings.Repeat("A", 44), "tfp_" + strings.Repeat("A", 44)},
		{"hubspot-private-app-token", "pat-na1-12345678-1234-1234-1234-123456789abc", "pat-na1-12345678-1234-1234-1234-123456789abc"},
		{"mailchimp-key", strings.Repeat("a", 32) + "-us12", strings.Repeat("a", 32) + "-us12"},
		{"klaviyo-key", "klaviyo pk_" + strings.Repeat("a", 34), "pk_" + strings.Repeat("a", 34)},
		{"razorpay-key", "rzp_live_AbCdEf12345678", "rzp_live_AbCdEf12345678"},
		{"nightfall-api-key", "NF-a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6", "NF-a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6"},
		{"endorlabs-token", "endr+AbCdEfGhIjKlMn12", "endr+AbCdEfGhIjKlMn12"},
		{"trufflehog-enterprise-key", "thog-key-0123456789abcdef", "thog-key-0123456789abcdef"},
		{"trufflehog-enterprise-secret", "thog-secret-0123456789abcdef0123456789abcdef", "thog-secret-0123456789abcdef0123456789abcdef"},
		{"tines-webhook", "https://acme.tines.com/webhook/0123456789abcdef0123456789abcdef/fedcba9876543210fedcba9876543210", "https://acme.tines.com/webhook/0123456789abcdef0123456789abcdef/fedcba9876543210fedcba9876543210"},
		{"pinecone-api-key", "pcsk_abc12_" + strings.Repeat("A", 63), "pcsk_abc12_" + strings.Repeat("A", 63)},
		{"langsmith-api-key", "lsv2_pt_" + strings.Repeat("a", 32) + "_" + strings.Repeat("b", 10), "lsv2_pt_" + strings.Repeat("a", 32) + "_" + strings.Repeat("b", 10)},
		{"langfuse-secret-key", "sk-lf-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "sk-lf-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"},
		{"elevenlabs-api-key", "elevenlabs sk_" + strings.Repeat("a", 48), "sk_" + strings.Repeat("a", 48)},
		{"xai-api-key", "xai-" + strings.Repeat("A", 80), "xai-" + strings.Repeat("A", 80)},
		{"voiceflow-api-key", "VF.DM." + strings.Repeat("a", 24) + "." + strings.Repeat("A", 16), "VF.DM." + strings.Repeat("a", 24) + "." + strings.Repeat("A", 16)},
		{"harness-pat", "harness pat." + strings.Repeat("A", 22) + "." + strings.Repeat("a", 24) + "." + strings.Repeat("B", 20), "pat." + strings.Repeat("A", 22) + "." + strings.Repeat("a", 24) + "." + strings.Repeat("B", 20)},
		{"zoho-crm-token", "1000." + strings.Repeat("a", 32) + "." + strings.Repeat("b", 32), "1000." + strings.Repeat("a", 32) + "." + strings.Repeat("b", 32)},
		{"intercom-access-token", "intercom_token=\"dG9rO" + strings.Repeat("A", 54) + "=\"", "dG9rO" + strings.Repeat("A", 54) + "="},
		{"front-api-token", "front_token=\"" + strings.Repeat("A", 36) + "." + strings.Repeat("B", 188) + "\"", strings.Repeat("A", 36) + "." + strings.Repeat("B", 188)},
		{"segment-api-key", "segment_key=\"" + strings.Repeat("A", 43) + "." + strings.Repeat("B", 43) + "\"", strings.Repeat("A", 43) + "." + strings.Repeat("B", 43)},
		{"posthog-personal-api-key", "phx_" + strings.Repeat("A", 43), "phx_" + strings.Repeat("A", 43)},
		{"launchdarkly-key", "api-123e4567-e89b-42d3-a456-426614174000", "api-123e4567-e89b-42d3-a456-426614174000"},
		{"postmark-token", "postmark_token=\"123e4567-e89b-12d3-a456-426614174000\"", "123e4567-e89b-12d3-a456-426614174000"},
		{"coda-api-token", "coda_api_key=\"123e4567-e89b-12d3-a456-426614174000\"", "123e4567-e89b-12d3-a456-426614174000"},
		{"calendly-api-key", "calendly_token=\"eyJ" + strings.Repeat("A", 120) + ".eyJ" + strings.Repeat("B", 120) + "." + strings.Repeat("C", 40) + "\"", "eyJ" + strings.Repeat("A", 120) + ".eyJ" + strings.Repeat("B", 120) + "." + strings.Repeat("C", 40)},
		{"monday-api-token", "monday_token=\"eyJ" + strings.Repeat("A", 30) + ".eyJ" + strings.Repeat("B", 150) + "." + strings.Repeat("C", 40) + "\"", "eyJ" + strings.Repeat("A", 30) + ".eyJ" + strings.Repeat("B", 150) + "." + strings.Repeat("C", 40)},
		{"flyio-token", "FlyV1 fm1_" + strings.Repeat("A", 520), "FlyV1 fm1_" + strings.Repeat("A", 520)},
		{"cloudflare-ca-key", "cloudflare v1.0-" + strings.Repeat("A", 171), "v1.0-" + strings.Repeat("A", 171)},
		{"artifactory-access-token", "AKCp" + strings.Repeat("A", 69), "AKCp" + strings.Repeat("A", 69)},
		{"artifactory-reference-token", "cmVmdGtu" + strings.Repeat("A", 56), "cmVmdGtu" + strings.Repeat("A", 56)},
		{"azure-app-config-connection-string", "Endpoint=https://demo-app.azconfig.io;Id=AbCdEfGhIjKlMnOpQrStUv==;Secret=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789+/==", "Endpoint=https://demo-app.azconfig.io;Id=AbCdEfGhIjKlMnOpQrStUv==;Secret=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789+/=="},
		{"azure-storage-connection-string", "DefaultEndpointsProtocol=https;AccountName=prodstorageacct;AccountKey=" + strings.Repeat("A", 86) + "==;EndpointSuffix=core.windows.net", "DefaultEndpointsProtocol=https;AccountName=prodstorageacct;AccountKey=" + strings.Repeat("A", 86) + "==;EndpointSuffix=core.windows.net"},
		{"azure-cosmosdb-connection-string", "AccountEndpoint=https://prod-cosmos.documents.azure.com:443/;AccountKey=" + strings.Repeat("A", 86) + "==;", "AccountEndpoint=https://prod-cosmos.documents.azure.com:443/;AccountKey=" + strings.Repeat("A", 86) + "==;"},
		{"azure-sas-url", "https://prodstorage.blob.core.windows.net/container/blob.txt?sp=r&st=2026-01-01T00:00:00Z&se=2026-12-31T23:59:59Z&spr=https&sv=2024-01-01&sr=b&sig=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789%2B", "https://prodstorage.blob.core.windows.net/container/blob.txt?sp=r&st=2026-01-01T00:00:00Z&se=2026-12-31T23:59:59Z&spr=https&sv=2024-01-01&sr=b&sig=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789%2B"},
		{"azure-function-key-url", "https://demo-func.azurewebsites.net/api/process?code=AbCdEfGhIjKlMnOpQrStUvWxYz0123456789_-", "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789_-"},
		{"spectralops-token", "spu-a1b2c3d4e5f6g7h8i9j0k1l2m3n4p5q6", "spu-a1b2c3d4e5f6g7h8i9j0k1l2m3n4p5q6"},
		{"atlassian-api-token", "ATCTT3xFfG" + strings.Repeat("A", 64) + "=12345678", "ATCTT3xFfG" + strings.Repeat("A", 64) + "=12345678"},
		{"jira-api-token", "ATATT" + strings.Repeat("A", 64) + "=12345678", "ATATT" + strings.Repeat("A", 64) + "=12345678"},
		{"salesforce-access-token", "salesforce 00D000000000001!" + strings.Repeat("A", 96), "00D000000000001!" + strings.Repeat("A", 96)},
		{"salesforce-refresh-token", "5AEP861" + strings.Repeat("A", 80), "5AEP861" + strings.Repeat("A", 80)},
		{"salesforce-consumer-key", "3MVG9" + strings.Repeat("A", 80), "3MVG9" + strings.Repeat("A", 80)},
		{"twilio-auth-token", "AC0123456789abcdef0123456789abcdef auth_token=\"0123456789abcdef0123456789abcdef\"", "0123456789abcdef0123456789abcdef"},
		{"mailjet-basic-auth", "mailjet basic auth " + strings.Repeat("A", 87) + "=", strings.Repeat("A", 87) + "="},
		{"okta-api-token", "tenant.okta.com token = 00abcdefghijklmnopqrstuvwxyz0123456789ABCD", "00abcdefghijklmnopqrstuvwxyz0123456789ABCD"},
		{"urlscan-api-key", "urlscan api_key = 123e4567-e89b-12d3-a456-426614174000", "123e4567-e89b-12d3-a456-426614174000"},
		{"openai-admin-key", "sk-admin-" + strings.Repeat("A", 58) + "T3BlbkFJ" + strings.Repeat("B", 58), "sk-admin-" + strings.Repeat("A", 58) + "T3BlbkFJ" + strings.Repeat("B", 58)},
		{"deepseek-api-key", "DEEPSEEK_API_KEY=\"sk-a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6\"", "sk-a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"},
		{"weightsandbiases-api-key", "WANDB_API_KEY=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"assemblyai-api-key", "ASSEMBLYAI_API_KEY=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"deepgram-api-key", "DEEPGRAM_API_KEY=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"edenai-api-key", "EDENAI_API_KEY=\"" + strings.Repeat("A", 36) + "." + strings.Repeat("B", 92) + "." + strings.Repeat("C", 43) + "\"", strings.Repeat("A", 36) + "." + strings.Repeat("B", 92) + "." + strings.Repeat("C", 43)},
		{"monkeylearn-api-key", "MONKEYLEARN_API_KEY=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"contentful-pat", "CFPAT-" + strings.Repeat("a", 43), "CFPAT-" + strings.Repeat("a", 43)},
		{"storyblok-personal-access-token", "storyblok_token=\"" + strings.Repeat("A", 22) + "tt-123456-" + strings.Repeat("B", 20) + "\"", strings.Repeat("A", 22) + "tt-123456-" + strings.Repeat("B", 20)},
		{"storyblok-access-token", "storyblok_access=\"" + strings.Repeat("A", 22) + "tt\"", strings.Repeat("A", 22) + "tt"},
		{"sanity-auth-token", "sanity_token=\"sk" + strings.Repeat("A", 79) + "\"", "sk" + strings.Repeat("A", 79)},
		{"elastic-email-api-key", "elasticemail_api_key=\"" + strings.Repeat("A", 96) + "\"", strings.Repeat("A", 96)},
		{"shortcut-api-token", "shortcut_token=\"123e4567-e89b-12d3-a456-426614174000\"", "123e4567-e89b-12d3-a456-426614174000"},
		{"webflow-api-key", "webflow_key=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"mapbox-secret-token", "mapbox_token=\"sk." + strings.Repeat("A", 90) + "\"", "sk." + strings.Repeat("A", 90)},
		{"locationiq-api-key", "locationiq_key=\"pk." + strings.Repeat("A", 32) + "\"", "pk." + strings.Repeat("A", 32)},
		{"coinapi-key", "X-CoinAPI-Key: ABCD1234-EF56-7890-ABCD-1234567890AB", "ABCD1234-EF56-7890-ABCD-1234567890AB"},
		{"etherscan-api-key", "etherscan apikey " + strings.Repeat("A", 34), strings.Repeat("A", 34)},
		{"bscscan-api-key", "bscscan apikey " + strings.Repeat("B", 34), strings.Repeat("B", 34)},
		{"guardian-api-key", "content.guardianapis.com api-key 12345678-abcd-1234-abcd-123456789abc", "12345678-abcd-1234-abcd-123456789abc"},
		{"circleci-pat", "CCIPAT_" + strings.Repeat("A", 22) + "_" + strings.Repeat("a", 40), "CCIPAT_" + strings.Repeat("A", 22) + "_" + strings.Repeat("a", 40)},
		{"sourcegraph-token", "sgp_0123456789abcdef_" + strings.Repeat("a", 40), "sgp_0123456789abcdef_" + strings.Repeat("a", 40)},
		{"sourcegraph-cody-token", "slk_" + strings.Repeat("a", 64), "slk_" + strings.Repeat("a", 64)},
		{"snyk-api-key", "SNYK_TOKEN=\"00000000-0000-4000-8000-000000000000\"", "00000000-0000-4000-8000-000000000000"},
		{"uptimerobot-api-key", "UPTIMEROBOT_API_KEY=\"FAKE12345-FAKE12345678901234567890\"", "FAKE12345-FAKE12345678901234567890"},
		{"sumologic-access-id", "sumologic access_id=\"suFAKE12345678\"", "suFAKE12345678"},
		{"sumologic-access-key", "sumologic access_key=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"statuspage-api-key", "statuspage token=\"00000000-0000-4000-8000-000000000000\"", "00000000-0000-4000-8000-000000000000"},
		{"sendinblue-api-key", "xkeysib-" + strings.Repeat("A", 81), "xkeysib-" + strings.Repeat("A", 81)},
		{"teamwork-token", "tkn.v1_" + strings.Repeat("A", 71) + "=", "tkn.v1_" + strings.Repeat("A", 71) + "="},
		{"salesblink-api-key", "salesblink_api_key=\"key-" + strings.Repeat("A", 64) + "\"", "key-" + strings.Repeat("A", 64)},
		{"smooch-app-key", "smooch_app_key=\"act_" + strings.Repeat("a", 24) + "\"", "act_" + strings.Repeat("a", 24)},
		{"mailmodo-api-key", "mailmodo_key=\"AAAAAAA-BBBBBBB-CCCCCCC-DDDDDDD\"", "AAAAAAA-BBBBBBB-CCCCCCC-DDDDDDD"},
		{"zapier-webhook", "https://hooks.zapier.com/hooks/catch/ABCDEF12/GHIJKLM", "https://hooks.zapier.com/hooks/catch/ABCDEF12/GHIJKLM"},
		{"deno-deploy-token", "ddp_" + strings.Repeat("A", 36), "ddp_" + strings.Repeat("A", 36)},
		{"supabase-management-token", "sbp_" + strings.Repeat("a", 40), "sbp_" + strings.Repeat("a", 40)},
		{"prefect-api-key", "pnu_" + strings.Repeat("A", 36), "pnu_" + strings.Repeat("A", 36)},
		{"figma-pat", "figd_" + strings.Repeat("A", 40), "figd_" + strings.Repeat("A", 40)},
		{"saladcloud-api-key", "salad_cloud_abc1234_" + strings.Repeat("A", 28), "salad_cloud_abc1234_" + strings.Repeat("A", 28)},
		{"planetscale-token", "pscale_tkn_" + strings.Repeat("A", 43), "pscale_tkn_" + strings.Repeat("A", 43)},
		{"planetscale-db-password", "pscale_pw_" + strings.Repeat("A", 43), "pscale_pw_" + strings.Repeat("A", 43)},
		{"databricks-token", "databricks dapi" + strings.Repeat("a", 32), "dapi" + strings.Repeat("a", 32)},
		{"portainer-token", "portainertoken=ptr_" + strings.Repeat("A", 32), "ptr_" + strings.Repeat("A", 32)},
		{"aws-appsync-api-key", "https://abcdefghijklmnopqrstuvwxyz.appsync-api.us-east-1.amazonaws.com/graphql api_key=da2-abcdefghijklmnopqrstuvwxyz", "da2-abcdefghijklmnopqrstuvwxyz"},
		{"azure-openai-key", "https://demo.openai.azure.com api-key=0123456789abcdef0123456789abcdef", "0123456789abcdef0123456789abcdef"},
		{"azure-batch-key", "https://acct.region.batch.azure.com key=" + strings.Repeat("A", 88), strings.Repeat("A", 88)},
		{"azure-container-registry-password", "myregistry.azurecr.io " + strings.Repeat("a", 42) + "+ACRbbbbbb", strings.Repeat("a", 42) + "+ACRbbbbbb"},
		{"gcp-service-account-json", `{"type":"service_account","private_key":"-----BEGIN PRIVATE KEY-----\nFAKE\n-----END PRIVATE KEY-----\n","client_email":"fake@proj.iam.gserviceaccount.com","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"}`, `{"type":"service_account","private_key":"-----BEGIN PRIVATE KEY-----\nFAKE\n-----END PRIVATE KEY-----\n","client_email":"fake@proj.iam.gserviceaccount.com","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"}`},
		{"gcp-application-default-credentials", `{"client_id":"fake.apps.googleusercontent.com","client_secret":"` + strings.Repeat("A", 24) + `","refresh_token":"` + strings.Repeat("B", 32) + `"}`, `{"client_id":"fake.apps.googleusercontent.com","client_secret":"` + strings.Repeat("A", 24) + `","refresh_token":"` + strings.Repeat("B", 32) + `"}`},
		{"redis-uri", "rediss://default:FakeRedisPass123@example.redis.cache.windows.net:6380", "rediss://default:FakeRedisPass123@example.redis.cache.windows.net:6380"},
		{"azure-redis-connection-string", "demo.redis.cache.windows.net:6380,password=" + strings.Repeat("A", 44) + ",ssl=True,abortConnect=False", "demo.redis.cache.windows.net:6380,password=" + strings.Repeat("A", 44) + ",ssl=True,abortConnect=False"},
		{"couchbase-capella-uri", "couchbases://user:Passw0rd!@cb.abc123.cloud.couchbase.com", "couchbases://user:Passw0rd!@cb.abc123.cloud.couchbase.com"},
		{"closecrm-api-key", "api_" + strings.Repeat("A", 45), "api_" + strings.Repeat("A", 45)},
		{"paystack-secret-key", "sk_test_" + strings.Repeat("A", 40), "sk_test_" + strings.Repeat("A", 40)},
		{"wrike-access-token", "wrike token ey" + strings.Repeat("A", 333), "ey" + strings.Repeat("A", 333)},
		{"twitter-consumer-secret", "twitter consumer_secret " + strings.Repeat("A", 50), strings.Repeat("A", 50)},
		{"facebook-oauth-secret", "facebook app_secret " + strings.Repeat("A", 32), strings.Repeat("A", 32)},
		{"flutterwave-secret-key", "FLWSECK-0123456789abcdef0123456789abcdef-X", "FLWSECK-0123456789abcdef0123456789abcdef-X"},
		{"pagarme-live-key", "ak_live_0123456789abcdefghijklmnopqrst", "ak_live_0123456789abcdefghijklmnopqrst"},
		{"rechargepayments-token", "sk_1x1_" + strings.Repeat("a", 64), "sk_1x1_" + strings.Repeat("a", 64)},
		{"lemonsqueezy-api-token", "lemonsqueezy token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9." + strings.Repeat("A", 314) + "." + strings.Repeat("B", 512), "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9." + strings.Repeat("A", 314) + "." + strings.Repeat("B", 512)},
		{"plaid-access-token", "access-sandbox-01234567-89ab-cdef-0123-456789abcdef", "access-sandbox-01234567-89ab-cdef-0123-456789abcdef"},
		{"cloudinary-url", "cloudinary://123456789012345:AbCdEfGhIjKlMnOpQrStUvWxYz1@demo-cloud", "cloudinary://123456789012345:AbCdEfGhIjKlMnOpQrStUvWxYz1@demo-cloud"},
		{"zendesk-api-token", "acme.zendesk.com ZENDESK_API_TOKEN=" + strings.Repeat("A", 40), strings.Repeat("A", 40)},
		{"freshdesk-api-key", "acme.freshdesk.com FRESHDESK_API_KEY=a1B2c3D4e5F6g7H8i9J0", "a1B2c3D4e5F6g7H8i9J0"},
		{"helpcrunch-api-key", "HELPCRUNCH_TOKEN=" + strings.Repeat("A", 328), strings.Repeat("A", 328)},
		{"line-messaging-token", "LINE_MESSAGING_TOKEN=" + strings.Repeat("A", 172), strings.Repeat("A", 172)},
		{"courier-api-key", "COURIER_AUTH_TOKEN=pk_live_" + strings.Repeat("A", 28), "pk_live_" + strings.Repeat("A", 28)},
		{"hashicorp-vault-approle", "vault role_id=11111111-2222-3333-4444-555555555555 secret_id=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"},
		{"mattermost-personal-token", "mattermost token abc123def456ghi789jkl012mn team.cloud.mattermost.com", "abc123def456ghi789jkl012mn"},
		{"cloudflare-global-api-key", "cloudflare global_api_key=0123456789abcdef0123456789abcdef01234", "0123456789abcdef0123456789abcdef01234"},
		{"docker-auth-config", `{"auths":{"ghcr.io":{"auth":"dXNlcjpwYXQxMjM0NTY3ODkw"}}}`, `"auths":{"ghcr.io":{"auth":"dXNlcjpwYXQxMjM0NTY3ODkw"`},
		{"azure-search-key", "https://acme.search.windows.net api-key: " + strings.Repeat("A", 52), strings.Repeat("A", 52)},
		{"azure-apim-subscription-key", "Ocp-Apim-Subscription-Key: 0123456789abcdef0123456789abcdef", "0123456789abcdef0123456789abcdef"},
		{"auth0-domain-jwt", "tenant.auth0.com token=eyJ" + strings.Repeat("A", 24) + ".eyJ" + strings.Repeat("B", 24) + "." + strings.Repeat("C", 24), "eyJ" + strings.Repeat("A", 24) + ".eyJ" + strings.Repeat("B", 24) + "." + strings.Repeat("C", 24)},
		{"virustotal-api-key", "virustotal_api_key=" + strings.Repeat("a", 64), strings.Repeat("a", 64)},
		{"shodan-api-key", "SHODAN_API_KEY=" + strings.Repeat("A", 32), strings.Repeat("A", 32)},
		{"securitytrails-api-key", "securitytrails_key=" + strings.Repeat("A", 32), strings.Repeat("A", 32)},
		{"snowflake-url", "snowflake://svc:Sup3rSecret@xy12345.us-east-1/db", "snowflake://svc:Sup3rSecret@xy12345.us-east-1/db"},
		{"sqlserver-connection-string", "Server=tcp:x.database.windows.net;User ID=app;Password=P@ssw0rd123;", "Server=tcp:x.database.windows.net;User ID=app;Password=P@ssw0rd123;"},
		{"rabbitmq-uri", "amqps://user:VerySecret123@mq.example/vhost", "amqps://user:VerySecret123@mq.example/vhost"},
		{"newsapi-key", "newsapi_key=0123456789abcdef0123456789abcdef", "0123456789abcdef0123456789abcdef"},
		{"openweather-api-key", "openweather APPID=0123456789abcdef0123456789abcdef", "0123456789abcdef0123456789abcdef"},
		{"tomorrowio-api-key", "tomorrow.io apikey=AbCdEfGhIjKlMnOpQrStUvWxYz123456", "AbCdEfGhIjKlMnOpQrStUvWxYz123456"},
		{"here-api-key", "platform.here.com apiKey " + strings.Repeat("A", 43), strings.Repeat("A", 43)},
		{"polygon-api-key", "POLYGON_API_KEY=" + strings.Repeat("A", 32), strings.Repeat("A", 32)},
		{"aws-session-token", "aws_session_token=\"" + strings.Repeat("A", 120) + "\"", strings.Repeat("A", 120)},
		{"alibaba-access-key", "alibaba access_key=LTAI" + strings.Repeat("A", 20), "LTAI" + strings.Repeat("A", 20)},
		{"scaleway-secret-key", "SCW_SECRET_KEY=11111111-2222-3333-4444-555555555555", "11111111-2222-3333-4444-555555555555"},
		{"github-oauth-client-secret", "github_oauth client_secret=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"github-app-private-key", "github_app_private_key = -----BEGIN PRIVATE KEY-----\nFAKEKEYDATA\n-----END PRIVATE KEY-----", "-----BEGIN PRIVATE KEY-----\nFAKEKEYDATA\n-----END PRIVATE KEY-----"},
		{"gitlab-oauth-client-secret", "gitlab_oauth client_secret=\"" + strings.Repeat("a", 64) + "\"", strings.Repeat("a", 64)},
		{"datadog-app-key", "DD_APP_KEY=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"braintree-access-token", "access_token$production$merchantid$" + strings.Repeat("A", 32), "access_token$production$merchantid$" + strings.Repeat("A", 32)},
		{"coinbase-cdp-api-key", "coinbase key=organizations/11111111-2222-3333-4444-555555555555/apiKeys/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "organizations/11111111-2222-3333-4444-555555555555/apiKeys/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"},
		{"webex-access-token", "webex access_token=" + strings.Repeat("A", 64) + "_AB12_11111111-2222-3333-4444-555555555555", strings.Repeat("A", 64) + "_AB12_11111111-2222-3333-4444-555555555555"},
		{"auth0-client-secret", "auth0 client_secret=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"onelogin-client-secret", "onelogin client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"detectify-api-key", "detectify api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"wiz-client-secret", "wiz client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"jupiterone-api-token", "jupiterone api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ldap-url", "ldaps://binduser:SuperSecretPassword@ldap.example.com/ou=people", "ldaps://binduser:SuperSecretPassword@ldap.example.com/ou=people"},
		{"loginradius-api-secret", "loginradius api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"stytch-secret", "secret-live-" + strings.Repeat("A", 40), "secret-live-" + strings.Repeat("A", 40)},
		{"openvpn-static-key", "-----BEGIN OpenVPN Static key V1-----\n" + strings.Repeat("a", 600) + "\n-----END OpenVPN Static key V1-----", "-----BEGIN OpenVPN Static key V1-----\n" + strings.Repeat("a", 600) + "\n-----END OpenVPN Static key V1-----"},
		{"azure-entra-client-secret", "AZURE_CLIENT_SECRET=client_secret=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"twitter-bearer-token", "twitter bearer_token=\"AAAA" + strings.Repeat("A", 100) + "\"", "AAAA" + strings.Repeat("A", 100)},
		{"twitch-client-secret", "twitch client_secret=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"twitch-access-token", "twitch access_token=\"" + strings.Repeat("a", 30) + "\"", strings.Repeat("a", 30)},
		{"ipinfo-token", "ipinfo token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"coinlayer-api-key", "coinlayer api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"coinlib-api-key", "coinlib api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"cryptocompare-api-key", "cryptocompare api_key=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"bitcoinaverage-api-key", "bitcoinaverage public_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"worldcoinindex-api-key", "worldcoinindex api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"blocknative-api-key", "blocknative api_key=\"" + strings.Repeat("A", 36) + "\"", strings.Repeat("A", 36)},
		{"fixerio-api-key", "fixer.io access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"currencylayer-api-key", "currencylayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"exchangerate-api-key", "exchangerate-api api_key=\"" + strings.Repeat("A", 24) + "\"", strings.Repeat("A", 24)},
		{"exchangeratesapi-api-key", "exchangeratesapi access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"currencyfreaks-api-key", "currencyfreaks api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"currencyscoop-api-key", "currencyscoop api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"fastforex-api-key", "fastforex api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"marketstack-api-key", "marketstack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"financialmodelingprep-api-key", "financialmodelingprep api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"finnhub-api-key", "finnhub api_key=\"" + strings.Repeat("A", 20) + "\"", strings.Repeat("A", 20)},
		{"tradier-token", "tradier access_token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"twelvedata-api-key", "twelvedata api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"vatlayer-api-key", "vatlayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"worldweather-api-key", "worldweatheronline api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"positionstack-api-key", "positionstack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"geocodio-api-key", "geocodio api_key=\"" + strings.Repeat("A", 39) + "\"", strings.Repeat("A", 39)},
		{"fastly-personal-token", "fastly personal_token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"telnyx-api-key", "telnyx api_key=KEY" + strings.Repeat("A", 40), "KEY" + strings.Repeat("A", 40)},
		{"vagrant-cloud-token", "vagrantcloud token=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"zeplin-token", "zeplin token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"vultr-api-key", "vultr api_key=\"" + strings.Repeat("a", 36) + "\"", strings.Repeat("a", 36)},
		{"bitly-access-token", "bitly access_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"algolia-admin-key", "algolia admin_api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"airbrake-project-key", "airbrake project_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"airbrake-user-key", "airbrake user_key=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"bugsnag-api-key", "bugsnag api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"infura-project-id", "infura project_id=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"messagebird-api-key", "messagebird api_key=live_ABCDEFGHIJKLMNOPQRSTUVWXY", "live_ABCDEFGHIJKLMNOPQRSTUVWXY"},
		{"pinata-jwt", "pinata jwt=\"eyJ" + strings.Repeat("A", 24) + ".eyJ" + strings.Repeat("B", 24) + "." + strings.Repeat("C", 24) + "\"", "eyJ" + strings.Repeat("A", 24) + ".eyJ" + strings.Repeat("B", 24) + "." + strings.Repeat("C", 24)},
		{"pushbullet-token", "pushbullet access_token=o." + strings.Repeat("A", 32), "o." + strings.Repeat("A", 32)},
		{"sendbird-api-token", "sendbird api_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"stormglass-api-key", "stormglass api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"todoist-api-token", "todoist token=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"uploadcare-secret-key", "uploadcare secret_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"browserstack-access-key", "browserstack access_key=\"" + strings.Repeat("A", 20) + "\"", strings.Repeat("A", 20)},
		{"cloudsmith-api-key", "cloudsmith api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"eventbrite-private-token", "eventbrite private_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"harvest-access-token", "harvest access_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"lokalise-token", "lokalise api_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"maxmind-license-key", "maxmind license_key=\"" + strings.Repeat("A", 16) + "\"", strings.Repeat("A", 16)},
		{"nylas-api-key", "nylas api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"pipedream-api-key", "pipedream api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"percy-token", "PERCY_TOKEN=token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"crowdin-token", "crowdin personal_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"postageapp-api-key", "postageapp api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"sendbird-organization-api-token", "sendbird organization_api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"checkly-api-key", "checkly api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"confluent-api-secret", "confluent api_secret=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"docusign-client-secret", "docusign client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gocardless-access-token", "gocardless access_token=live_" + strings.Repeat("A", 48), "live_" + strings.Repeat("A", 48)},
		{"gumroad-access-token", "gumroad access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"hellosign-api-key", "hellosign api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"mailboxlayer-api-key", "mailboxlayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"mediastack-api-key", "mediastack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"opencage-api-key", "opencage api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"packagecloud-token", "packagecloud token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"phrase-access-token", "phrase access_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"semaphore-api-token", "semaphore api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"scrutinizer-token", "scrutinizer token=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"saucelabs-access-key", "saucelabs access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"lessannoyingcrm-api-key", "lessannoyingcrm api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"meaningcloud-api-key", "meaningcloud api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"openuv-api-key", "openuv api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"pandascore-api-key", "pandascore api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"paperform-api-key", "paperform api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"parsehub-api-key", "parsehub api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"pdfshift-api-key", "pdfshift api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"peopledatalabs-api-key", "peopledatalabs api_key=\"" + strings.Repeat("A", 64) + "\"", strings.Repeat("A", 64)},
		{"plivo-auth-token", "plivo auth_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"rapidapi-key", "rapidapi x-rapidapi-key=\"" + strings.Repeat("A", 50) + "\"", strings.Repeat("A", 50)},
		{"scraperapi-key", "scraperapi api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"scrapestack-api-key", "scrapestack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"scrapingbee-api-key", "scrapingbee api_key=\"" + strings.Repeat("A", 80) + "\"", strings.Repeat("A", 80)},
		{"serpstack-api-key", "serpstack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"shotstack-api-key", "shotstack api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"signalwire-api-token", "signalwire api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"testingbot-secret", "testingbot secret=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"abstract-api-key", "abstract api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"alchemy-api-key", "alchemy api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"apify-token", "apify token=apify_api_" + strings.Repeat("A", 40), "apify_api_" + strings.Repeat("A", 40)},
		{"apilayer-key", "apilayer access_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"bannerbear-api-key", "bannerbear api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"baremetrics-api-key", "baremetrics api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"beamer-api-key", "beamer api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"bitbar-api-key", "bitbar api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"blazemeter-api-key", "blazemeter api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"buttercms-api-token", "buttercms api_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"canny-api-key", "canny api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"chartmogul-api-key", "chartmogul api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"clearbit-api-key", "clearbit api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"clockify-api-key", "clockify api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloudconvert-api-key", "cloudconvert api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloudmersive-api-key", "cloudmersive api_key=12345678-1234-1234-1234-123456789abc", "12345678-1234-1234-1234-123456789abc"},
		{"convertapi-secret", "convertapi secret=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"convertkit-api-secret", "convertkit api_secret=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"dailyco-api-key", "daily.co api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"deepai-api-key", "deepai api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"delighted-api-key", "delighted api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"deputy-api-token", "deputy access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fullstory-api-key", "fullstory api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"geoapify-api-key", "geoapify api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"graphhopper-api-key", "graphhopper api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"hunter-api-key", "hunter api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"imagekit-private-key", "imagekit private_key=private_" + strings.Repeat("A", 32), "private_" + strings.Repeat("A", 32)},
		{"kickbox-api-key", "kickbox api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"klipfolio-api-key", "klipfolio api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"lob-api-key", "lob api_key=live_" + strings.Repeat("A", 35), "live_" + strings.Repeat("A", 35)},
		{"moosend-api-key", "moosend api_key=12345678-1234-1234-1234-123456789abc", "12345678-1234-1234-1234-123456789abc"},
		{"neutrinoapi-api-key", "neutrinoapi api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"numverify-api-key", "numverify access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"omnisend-api-key", "omnisend api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"owlbot-api-key", "owlbot token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"pandadoc-api-key", "pandadoc api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"partnerstack-api-key", "partnerstack token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"pastebin-api-key", "pastebin api_dev_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"paymongo-secret-key", "paymongo secret_key=sk_live_" + strings.Repeat("A", 40), "sk_live_" + strings.Repeat("A", 40)},
		{"photoroom-api-key", "photoroom api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"proxycrawl-api-token", "proxycrawl token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"qase-api-token", "qase api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"rebrandly-api-key", "rebrandly api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"repairshopr-api-key", "repairshopr api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"replyio-api-key", "reply.io api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"restpack-htmltopdf-api-key", "restpack htmltopdf api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"restpack-screenshot-api-key", "restpack screenshot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"rocketreach-api-key", "rocketreach api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"route4me-api-key", "route4me api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"salesflare-api-key", "salesflare api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"adzuna-api-key", "adzuna app_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"airvisual-api-key", "airvisual api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"amadeus-api-secret", "amadeus client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ambee-api-key", "ambee api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"amplitude-api-key", "amplitude api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"apiflash-access-key", "apiflash access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"apitemplate-api-key", "apitemplate api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"appcues-api-key", "appcues api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"appfollow-api-key", "appfollow token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"autoklose-api-key", "autoklose api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"aviationstack-api-key", "aviationstack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"ayrshare-api-key", "ayrshare api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"besttime-api-key", "besttime api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"brandfetch-api-key", "brandfetch token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"browshot-api-key", "browshot api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"calendarific-api-key", "calendarific api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"carboninterface-api-key", "carbon interface token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"craftmypdf-api-key", "craftmypdf api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"currentsapi-api-key", "currentsapi api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"debounce-api-key", "debounce api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"detectlanguage-api-key", "detectlanguage api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"clarifai-api-key", "clarifai pat=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clicksend-api-key", "clicksend api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"codemagic-api-token", "codemagic api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"databox-api-token", "databox token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"diffbot-api-token", "diffbot token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"edamam-api-key", "edamam app_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"ethplorer-api-key", "ethplorer api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"faceplusplus-api-key", "faceplusplus api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"geckoboard-api-key", "geckoboard api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"hasura-admin-secret", "hasura admin_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"holidayapi-key", "holidayapi key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"html2pdf-api-key", "html2pdf api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"ip2location-api-key", "ip2location api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"ipapi-api-key", "ipapi access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"ipinfodb-api-key", "ipinfodb api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"jotform-api-key", "jotform api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"keenio-api-key", "keen.io master_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"languagelayer-api-key", "languagelayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"linenotify-token", "line notify token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"linkpreview-api-key", "linkpreview api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"vercel-token", "VERCEL_TOKEN=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"railway-token", "railway_token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"travisci-token", "TRAVIS_TOKEN=\"" + strings.Repeat("A", 22) + "\"", strings.Repeat("A", 22)},
		{"betterstack-api-key", "betterstack_api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"customerio-api-key", "customer.io key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"trello-api-key", "trello_api_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"helpscout-api-key", "helpscout key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"mailerlite-api-key", "mailerlite_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"mandrill-api-key", "mandrill_key=\"" + strings.Repeat("A", 22) + "\"", strings.Repeat("A", 22)},
		{"onesignal-api-key", "onesignal_rest_api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"copper-api-key", "copper_api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"capsulecrm-api-key", "capsulecrm_api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"apollo-api-key", "apollo_api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"lemlist-api-key", "lemlist_api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"getresponse-api-key", "getresponse_api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"alienvault-otx-api-key", "alienvault_otx_key=\"" + strings.Repeat("a", 64) + "\"", strings.Repeat("a", 64)},
		{"censys-api-key", "censys_api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"vpnapi-key", "vpnapi.io key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"ipqualityscore-api-key", "ipqualityscore key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"ipstack-api-key", "ipstack key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"ipgeolocation-api-key", "ipgeolocation key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"zerotier-api-token", "zerotier token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"logzio-token", "logz.io token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"codeclimate-token", "codeclimate repo token=\"" + strings.Repeat("a", 64) + "\"", strings.Repeat("a", 64)},
		{"codacy-api-token", "codacy token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"coveralls-repo-token", "coveralls token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"weatherstack-api-key", "weatherstack key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"accuweather-api-key", "accuweather key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"weatherbit-api-key", "weatherbit key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"mapquest-api-key", "mapquest key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"aiven-token", "aiven_token=\"" + strings.Repeat("A", 372) + "\"", strings.Repeat("A", 372)},
		{"abuseipdb-api-key", "abuseipdb_key=\"" + strings.Repeat("a", 80) + "\"", strings.Repeat("a", 80)},
		{"sonarcloud-token", "SONAR_TOKEN=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"jumpcloud-api-key", "jumpcloud_api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"pipedrive-api-token", "pipedrive_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"sparkpost-api-key", "sparkpost_api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"dropbox-token", "sl.u." + strings.Repeat("A", 140), "sl.u." + strings.Repeat("A", 140)},
		{"readme-api-key", "rdme_" + strings.Repeat("a", 70), "rdme_" + strings.Repeat("a", 70)},
		{"rootly-api-key", "rootly_" + strings.Repeat("a", 64), "rootly_" + strings.Repeat("a", 64)},
		{"web3storage-token", "web3 " + "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ" + strings.Repeat("A", 120) + "." + strings.Repeat("B", 40), "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ" + strings.Repeat("A", 120) + "." + strings.Repeat("B", 40)},
		{"stripe-payment-intent-client-secret", "pi_" + strings.Repeat("A", 24) + "_secret_" + strings.Repeat("B", 25), "pi_" + strings.Repeat("A", 24) + "_secret_" + strings.Repeat("B", 25)},
		{"checkout-secret-key", "checkout sk_test_12345678-1234-1234-1234-123456789abc", "sk_test_12345678-1234-1234-1234-123456789abc"},
		{"loggly-token", "loggly customer_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"mixpanel-api-secret", "mixpanel api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mockaroo-api-key", "mockaroo api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"mux-token-secret", "mux token_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nutritionix-api-key", "nutritionix app_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"oanda-api-token", "oanda api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"onfleet-api-key", "onfleet api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"pdflayer-api-key", "pdflayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"pepipost-api-key", "pepipost api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"pivotaltracker-api-token", "pivotal tracker api_token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"pixabay-api-key", "pixabay api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"podio-api-token", "podio access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"pubnub-publish-key", "pubnub publish_key=pub-c-" + strings.Repeat("A", 36), "pub-c-" + strings.Repeat("A", 36)},
		{"pubnub-subscribe-key", "pubnub subscribe_key=sub-c-" + strings.Repeat("A", 36), "sub-c-" + strings.Repeat("A", 36)},
		{"pusher-channel-key", "pusher channel_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"qualaroo-api-key", "qualaroo api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"rawg-api-key", "rawg api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"ringcentral-client-secret", "ringcentral client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"scrapeowl-api-key", "scrapeowl api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"scrapfly-api-key", "scrapfly api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"screenshotapi-key", "screenshotapi api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"screenshotlayer-api-key", "screenshotlayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"selectpdf-api-key", "selectpdf api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"sheety-api-key", "sheety bearer_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"shipday-api-key", "shipday api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"signable-api-key", "signable api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"signaturit-api-key", "signaturit token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"simplesat-api-key", "simplesat api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"smartystreets-auth-token", "smarty streets auth_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"snipcart-api-key", "snipcart secret_api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"spoonacular-api-key", "spoonacular api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"sportsmonk-api-token", "sportsmonk api_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"spotify-client-secret", "spotify client_secret=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"statuscake-api-key", "statuscake api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"stockdata-api-key", "stockdata token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"storychief-api-key", "storychief api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"strava-client-secret", "strava client_secret=\"" + strings.Repeat("a", 40) + "\"", strings.Repeat("a", 40)},
		{"swiftype-api-key", "swiftype api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"tatum-api-key", "tatum api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"taxjar-api-token", "taxjar api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"textmagic-api-key", "textmagic api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"tiingo-api-token", "tiingo api_token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"timecamp-api-token", "timecamp token=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"timezoneapi-key", "timezoneapi api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"toggltrack-api-token", "toggltrack api_token=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"tomtom-api-key", "tomtom key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"transferwise-api-token", "transferwise api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"unsplash-access-key", "unsplash access_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"userstack-api-key", "userstack access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"visualcrossing-api-key", "visual crossing api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"voicegain-api-key", "voicegain api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"wepay-client-secret", "wepay client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"yandex-api-key", "yandex api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"yelp-api-key", "yelp bearer_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ynab-api-token", "ynab personal_access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"zenrows-api-key", "zenrows api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"zenscrape-api-key", "zenscrape api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"zenserp-api-key", "zenserp api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"zerobounce-api-key", "zerobounce api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"zipcodebase-api-key", "zipcodebase api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"bitfinex-api-secret", "bitfinex api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"bitmex-api-secret", "bitmex secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kucoin-api-secret", "kucoin api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"smartsheet-access-token", "smartsheet access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"tableau-pat-secret", "tableau pat_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"thousandeyes-token", "thousandeyes bearer_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ticketmaster-api-key", "ticketmaster consumer_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"theoddsapi-key", "the odds api api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"thinkific-api-key", "thinkific api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ubidots-token", "ubidots token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"uclassify-api-key", "uclassify api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"upcdatabase-api-key", "upc database api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"uplead-api-key", "uplead api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"vbout-api-key", "vbout api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"veriphone-api-key", "veriphone api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"walkscore-api-key", "walk score api_key=\"" + strings.Repeat("A", 32) + "\"", strings.Repeat("A", 32)},
		{"websitepulse-api-key", "websitepulse api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"whoxy-api-key", "whoxy api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"wistia-api-token", "wistia api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"wit-ai-token", "wit.ai server_access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ticket-tailor-api-key", "ticket tailor api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"tmetric-api-token", "tmetric api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"teamgate-api-key", "teamgate api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"teamworkspaces-token", "teamwork spaces token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"signupgenius-api-key", "signup genius api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"speechtextai-api-key", "speechtext.ai api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sirv-api-token", "sirv api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"siteleaf-api-key", "siteleaf api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"skrapp-api-key", "skrapp api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"skybiometry-api-key", "skybiometry api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"simplynoted-api-key", "simply noted api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"simvoly-api-key", "simvoly api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sinch-message-api-token", "sinch message_api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sslmate-api-key", "sslmate api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"statuspal-api-key", "statuspal api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"storecove-api-key", "storecove token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"stormboard-api-key", "stormboard api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"streak-api-key", "streak api_key=\"" + strings.Repeat("A", 40) + "\"", strings.Repeat("A", 40)},
		{"stripo-api-key", "stripo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sugester-api-token", "sugester api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"abyssale-api-key", "abyssale api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"adafruit-io-key", "adafruit io aio_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"adobe-io-client-secret", "adobe io client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"aeroworkflow-api-key", "aero workflow api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"agora-app-certificate", "agora app_certificate=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"airship-api-key", "airship master_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"alconost-api-key", "alconost api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"alegra-api-token", "alegra api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"aletheia-api-key", "aletheia api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"allsports-api-key", "all sports api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"anypoint-client-secret", "anypoint client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apacta-api-key", "apacta api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"api2cart-api-key", "api2cart api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apideck-api-key", "apideck api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apifonica-api-key", "apifonica api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apimatic-api-key", "apimatic api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apimetrics-api-key", "apimetrics api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"appointedd-api-key", "appointedd api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"appoptics-api-token", "appoptics api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"appsynergy-api-key", "app synergy api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"apptivo-api-key", "apptivo access_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"artsy-api-token", "artsy api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"atera-api-key", "atera api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"atlassian-datacenter-token", "atlassian data center personal_access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"audd-api-token", "audd api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"autodesk-client-secret", "autodesk client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"autopilot-api-key", "autopilot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"axonaut-api-key", "axonaut api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"aylien-api-key", "aylien application_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"beebole-api-token", "beebole api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"besnappy-api-key", "be snappy api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"billomat-api-key", "billomat api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"blitapp-api-key", "blitapp api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"blogger-api-key", "blogger api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"bombbomb-api-key", "bomb bomb api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"boostnote-api-token", "boost note api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"borgbase-api-key", "borgbase api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"buddyns-api-key", "buddy ns api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"budibase-api-key", "budibase api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"bugherd-api-key", "bugherd api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"bulbul-api-key", "bulbul api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"bulksms-api-token", "bulk sms api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"caflou-api-key", "caflou api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"calorieninja-api-key", "calorie ninjas api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"campayn-api-key", "campayn api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"captaindata-api-key", "captain data api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cashboard-api-key", "cashboard api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"caspio-api-key", "caspio client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"centralstationcrm-api-token", "central station crm api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cexio-api-key", "cex.io api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"chatbot-api-key", "chatbot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"chatfuel-api-key", "chatfuel api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"chec-api-key", "chec.io secret_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"checkvist-api-token", "checkvist api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cicero-api-key", "cicero api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clickhelp-api-key", "clickhelp api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cliengo-api-key", "cliengo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clientary-api-key", "clientary api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clinchpad-api-key", "clinchpad api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clockworksms-api-key", "clockwork sms api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"avaza-api-token", "avaza api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloudelements-api-key", "cloud elements user_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloudimage-api-key", "cloudimage api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloudplan-api-key", "cloudplan api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloverly-api-key", "cloverly api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"cloze-api-key", "cloze api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"clustdoc-api-key", "clustdoc api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"codequiry-api-key", "codequiry api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"collect2-api-key", "collect2 api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"column-api-key", "column secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"commercejs-api-key", "commerce.js secret_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"commodities-api-key", "commodities access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"companyhub-api-key", "company hub api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"conversiontools-api-key", "conversion tools api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"convier-api-key", "convier api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"countrylayer-api-key", "countrylayer access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"currencycloud-api-key", "currency cloud api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"customerguru-api-key", "customer.guru api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"d7network-api-token", "d7 network api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dandelion-api-key", "dandelion app_id=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dareboost-api-key", "dareboost api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"datagov-api-key", "data.gov api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"demio-api-key", "demio secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dfuse-api-key", "dfuse token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"diggernaut-api-key", "diggernaut api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"disqus-api-key", "disqus api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ditto-api-key", "ditto api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dnscheck-api-key", "dns check api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"docparser-api-key", "docparser api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"documo-api-key", "documo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dotdigital-api-key", "dot digital password=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dovico-api-key", "dovico api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dronahq-api-key", "drona hq api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"droneci-token", "drone ci token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"duply-api-key", "duply api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dynalist-api-token", "dynalist api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dyspatch-api-key", "dyspatch api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"eagleeyenetworks-api-key", "eagle eye networks secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"easyinsight-api-key", "easy insight api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ecostruxureit-api-key", "ecostruxure it api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"eightxeight-api-key", "8x8 api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"dwolla-api-key", "dwolla client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"enablex-api-key", "enablex secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"enigma-api-key", "enigma api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"envoy-api-key", "envoy api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"eraser-api-key", "eraser api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"everhour-api-key", "everhour api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"exportsdk-api-key", "export sdk api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"extractorapi-key", "extractor api api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"feedier-api-key", "feedier api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fetchrss-api-key", "fetch rss api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fibery-api-token", "fibery api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fileio-api-key", "file.io api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"finage-api-key", "finage api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"findl-api-key", "findl api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flatio-api-key", "flatio api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fleetbase-api-key", "fleetbase secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flexport-api-key", "flexport api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flickr-api-key", "flickr api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flightapi-key", "flight api api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flightlabs-api-key", "flight labs access_key=\"" + strings.Repeat("a", 32) + "\"", strings.Repeat("a", 32)},
		{"flightstats-api-key", "flight stats app_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"float-api-key", "float api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"flowflu-api-key", "flowlu api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fmfw-api-key", "fmfw secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"formbucket-api-key", "form bucket api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"formcraft-api-key", "form craft api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"formio-api-key", "form.io jwt_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"formsite-api-key", "formsite api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"foursquare-api-key", "foursquare client_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"frameio-api-token", "frame.io api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"freshbooks-api-key", "fresh books token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fulcrum-api-token", "fulcrum api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"fxmarket-api-key", "fx market api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gengo-api-key", "gengo private_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"geocodify-api-key", "geocodify api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"geoipifi-api-key", "geo.ipify api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"getemail-api-key", "get email api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"getemails-api-key", "get emails api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"getgeoapi-key", "get geo api api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"getgist-api-key", "get gist api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"getsandbox-api-key", "get sandbox api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gitter-token", "gitter access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"glassnode-api-key", "glassnode api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gocanvas-api-key", "go canvas api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"godaddy-api-key", "go daddy secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"goodday-api-key", "good day api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"graphcms-api-token", "graph cms auth_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"groovehq-api-key", "groove hq api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gtmetrix-api-key", "gtmetrix api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"guru-api-key", "guru api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"gyazo-api-token", "gyazo access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"happyscribe-api-key", "happy scribe api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"hive-api-key", "hive api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"hiveage-api-key", "hiveage api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"holistic-api-key", "holistic api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"humanity-api-key", "humanity api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"hybiscus-api-key", "hybiscus api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"hypertrack-api-key", "hypertrack secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ibmcloud-user-key", "ibm cloud user_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"iconfinder-api-key", "iconfinder api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"iexapis-api-key", "iex apis api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"iexcloud-api-key", "iex cloud secret_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"imagga-api-key", "imagga api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"impala-api-key", "impala secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"insightly-api-key", "insightly api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"instabot-api-key", "instabot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"instamojo-api-key", "instamojo auth_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"interseller-api-key", "interseller api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"intra42-api-key", "intra42 api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"intrinio-api-key", "intrinio api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"invoiceocean-api-key", "invoice ocean api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"juro-api-key", "juro token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kanban-api-key", "kanban api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kanbantool-api-key", "kanban tool api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"karmacrm-api-key", "karma crm api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"knapsackpro-api-token", "knapsack pro api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kontent-api-key", "kontent management_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kylas-api-key", "kylas api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"leadfeeder-api-key", "leadfeeder api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"lendflow-api-key", "lendflow secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"lexigram-api-key", "lexigram api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"kraken-api-secret", "kraken api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"larksuite-token", "larksuite tenant_access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"liveagent-api-key", "live agent api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"livestorm-api-key", "livestorm api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"loadmill-api-key", "loadmill api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"loyverse-api-token", "loyverse api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"lunchmoney-api-token", "lunch money api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"luno-api-secret", "luno api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"m3o-api-key", "m3o api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"madkudu-api-key", "madkudu api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"magicbell-api-key", "magic bell secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"magnetic-api-key", "magnetic api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mailjetsms-api-token", "mailjet sms api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mailsac-api-key", "mailsac api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"manifest-api-key", "manifest api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mavenlink-api-token", "mavenlink api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"meistertask-api-token", "meister task api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"meraki-api-key", "meraki api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mesibo-api-token", "mesibo api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"metaapi-token", "meta api token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"metabase-api-key", "metabase session=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"metrilo-api-key", "metrilo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mindmeister-api-token", "mind meister api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"miro-api-token", "miro access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mite-api-key", "mite api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mixmax-api-key", "mixmax api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"moderation-api-key", "moderation api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"moonclerk-api-key", "moon clerk secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"moralis-api-key", "moralis api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"mrticktock-api-key", "mr tick tock api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"myfreshworks-api-key", "myfreshworks api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"myintervals-api-key", "my intervals api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nasdaqdatalink-api-key", "nasdaq data link api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nethunt-api-key", "net hunt api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"netsuite-token-secret", "net suite token_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"newscatcher-api-key", "news catcher api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nexmo-api-key", "nexmo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nftport-api-key", "nft port api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ngc-api-key", "nvidia ngc api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nicereply-api-key", "nice reply api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nimble-api-key", "nimble api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"noticeable-api-key", "noticeable api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nozbeteams-api-token", "nozbe teams api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"nvapi-key", "nvapi api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"onedesk-api-key", "one desk api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"onepagecrm-api-key", "one page crm api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"oopspam-api-key", "oopspam api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"optimizely-api-key", "optimizely sdk_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"overloop-api-key", "overloop api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"paralleldots-api-key", "parallel dots api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"parsers-api-key", "parsers api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"parseur-api-key", "parseur api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"paydirt-api-key", "paydirt api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"paymo-api-key", "paymo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"planview-leankit-api-key", "planview leankit api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"planyo-api-key", "planyo api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"pollsapi-key", "polls api api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"poloniex-api-secret", "poloniex api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"postbacks-api-key", "postbacks api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"powrbot-api-key", "powrbot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"privacy-api-key", "privacy.com api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"prodpad-api-key", "prodpad api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"prospectcrm-api-key", "prospect crm api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"protocolsio-api-token", "protocols.io api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"purestake-api-key", "purestake api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"qubole-api-token", "qubole api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ramp-api-key", "ramp secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"raven-api-key", "raven api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"reachmail-api-key", "reach mail api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"reallysimplesystems-api-key", "really simple systems api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"refiner-api-key", "refiner api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"rentman-api-token", "rentman api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"requestfinance-api-key", "request finance secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"rev-ai-api-key", "rev.ai api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"revampcrm-api-key", "revamp crm api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"ritekit-api-key", "ritekit api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"roaring-api-key", "roaring api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"robinhoodcrypto-api-secret", "robinhood crypto api_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"rownd-api-key", "rownd secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"runrunit-api-key", "runrun.it api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"salescookie-api-key", "sales cookie api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"salesmate-api-key", "salesmate api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"satismeter-project-key", "satis meter project_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"satismeter-write-key", "satis meter write_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"scalr-api-key", "scalr secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"scraperbox-api-key", "scraper box api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"scrapingant-api-key", "scraping ant api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"serphouse-api-key", "serp house api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sherpadesk-api-key", "sherpa desk api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"shutterstock-api-token", "shutterstock access_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"sigopt-api-token", "sigopt client_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"simfin-api-key", "simfin api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"square-app-secret", "square app_secret=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"squarespace-api-key", "squarespace api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"stitchdata-api-token", "stitch data api_token=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"supernotes-api-key", "supernotes api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"surveyanyplace-api-key", "survey anyplace api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"surveybot-api-key", "survey bot api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"surveysparrow-api-key", "survey sparrow api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"survicate-api-key", "survicate api_key=\"" + strings.Repeat("A", 48) + "\"", strings.Repeat("A", 48)},
		{"aha-api-key", "example.aha.io token=" + strings.Repeat("a", 64), strings.Repeat("a", 64)},
		{"larksuite-app-secret", "larksuite app_id=cli_ABCDEFGHIJKLMNOP app_secret=" + strings.Repeat("A", 32), strings.Repeat("A", 32)},
	}

	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			if !registryFinds(tc.id, tc.input, tc.secret) {
				t.Fatalf("expected %s to find %q in %q", tc.id, tc.secret, tc.input)
			}
		})
	}
}

func registryFinds(id, input, secret string) bool {
	for _, d := range DefaultRegistry() {
		for _, c := range d.Detect([]byte(input)) {
			if c.DetectorID == id && c.Secret == secret {
				return true
			}
		}
	}
	return false
}

func TestRedact(t *testing.T) {
	got := Redact("abcdefghijklmnop")
	if got != "abcd********mnop" {
		t.Fatalf("unexpected redaction: %q", got)
	}
}

func TestPlausibleSecretRejectsRegexFragments(t *testing.T) {
	if plausibleSecret(`[^\s*\"]+`) {
		t.Fatal("expected regex fragment to be rejected")
	}
}

func TestLoadCustomFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "detectors.json")
	err := os.WriteFile(path, []byte(`{
		"detectors": [{
			"id": "internal",
			"name": "Internal",
			"keywords": ["internal_key"],
			"regex": "internal_key=([a-z0-9]{16})",
			"secret_group": 1
		}]
	}`), 0o600)
	if err != nil {
		t.Fatal(err)
	}

	ds, err := LoadCustomFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(ds) != 1 {
		t.Fatalf("expected one detector, got %d", len(ds))
	}
	candidates := ds[0].Detect([]byte("internal_key=abcdefghijklmnop"))
	if len(candidates) != 1 || candidates[0].Secret != "abcdefghijklmnop" {
		t.Fatalf("unexpected candidates: %#v", candidates)
	}
}

func TestRegistryInfo(t *testing.T) {
	infos := RegistryInfo(DefaultRegistry())
	if len(infos) == 0 {
		t.Fatal("expected detector info")
	}
	if infos[0].ID == "" || infos[0].Name == "" || infos[0].Severity == "" {
		t.Fatalf("incomplete detector info: %#v", infos[0])
	}
}
