package detectors

type VerificationAuditStatus string

const (
	VerificationAuditReviewed          VerificationAuditStatus = "reviewed"
	VerificationAuditRequiresHardening VerificationAuditStatus = "requires_hardening"
	VerificationAuditBlocked           VerificationAuditStatus = "blocked"
	VerificationAuditPending           VerificationAuditStatus = "pending_review"
	VerificationAuditNoVerifier        VerificationAuditStatus = "no_verifier"
)

type VerificationAuditEntry struct {
	ID                 string                  `json:"id"`
	Name               string                  `json:"name"`
	Verifiable         bool                    `json:"verifiable"`
	VerificationSafety VerificationSafety      `json:"verification_safety,omitempty"`
	AuditStatus        VerificationAuditStatus `json:"audit_status"`
	AuditBatch         int                     `json:"audit_batch,omitempty"`
	Notes              string                  `json:"notes,omitempty"`
}

type VerificationAuditReport struct {
	Total             int                      `json:"total"`
	Reviewed          int                      `json:"reviewed"`
	RequiresHardening int                      `json:"requires_hardening"`
	Blocked           int                      `json:"blocked"`
	PendingReview     int                      `json:"pending_review"`
	NoVerifier        int                      `json:"no_verifier"`
	Entries           []VerificationAuditEntry `json:"entries"`
}

type verificationAuditAssessment struct {
	Status VerificationAuditStatus
	Batch  int
	Notes  string
}

var verificationAuditAssessments = map[string]verificationAuditAssessment{
	"aws-credentials":         {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"github-token":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"github-pat-v2":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"slack-token":             {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"stripe-key":              {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"anthropic-key":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"sendgrid-key":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"mailgun-key":             {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"gitlab-token":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"discord-token":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"discord-bot-token":       {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"telegram-bot-token":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"npm-token":               {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"datadog-api-key":         {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"datadog-credentials":     {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"new-relic-key":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"heroku-api-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"cloudflare-api-token":    {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"digitalocean-token":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"azure-devops-pat":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"terraform-cloud-token":   {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"netlify-token":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"pulumi-token":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"doppler-token":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"tailscale-key":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"rubygems-api-key":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"linear-api-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"notion-token":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"postman-api-key":         {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"slack-webhook":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"sentry-user-token":       {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"sentry-org-token":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"twilio-auth-token":       {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"openai-admin-key":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"shortcut-api-token":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"circleci-pat":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"azure-entra-credentials": {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"fastly-personal-token":   {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"bitly-access-token":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"todoist-api-token":       {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"tinypng-api-key":         {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"cloudsmith-api-key":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"scraperapi-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"scrapestack-api-key":     {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"apify-token":             {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"deepai-api-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"proxycrawl-api-token":    {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"rebrandly-api-key":       {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"carboninterface-api-key": {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"html2pdf-api-key":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"pdflayer-api-key":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"scrapfly-api-key":        {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"screenshotlayer-api-key": {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"oopspam-api-key":         {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"vercel-token":            {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"railway-token":           {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"travisci-token":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"censys-credentials":      {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"readme-api-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"rootly-api-key":          {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},
	"larksuite-app-secret":    {Status: VerificationAuditReviewed, Notes: "Pre-systematic safety review."},

	"google-api-key":    {Status: VerificationAuditBlocked, Batch: 1, Notes: "Generic Google keys cannot be validated reliably against a single provider API."},
	"ngrok-token":       {Status: VerificationAuditBlocked, Batch: 1, Notes: "Detected credential families do not share a proven verification contract."},
	"langsmith-api-key": {Status: VerificationAuditBlocked, Batch: 1, Notes: "Cloud region, service-key tenant context, and self-hosted endpoint context are unresolved."},

	"openai-key":                {Status: VerificationAuditReviewed, Batch: 1, Notes: "Admin keys are routed separately; model-list success is schema-validated and suppressed."},
	"pagerduty-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Split REST tokens from routing and integration keys before promotion."},
	"buildkite-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Route API, portal, and cluster-agent token variants independently."},
	"square-token":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "Detected prefixed access tokens use schema-classified production and sandbox merchant requests; application secrets are rejected locally."},
	"discord-webhook":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Webhook metadata identity is schema-validated and suppressed."},
	"grafana-token":             {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Grafana Cloud region context is incomplete."},
	"honeycomb-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Split key formats and correlate US or EU endpoint context."},
	"opsgenie-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Correlate global or EU endpoint context and harden restricted-key classification."},
	"webex-bot-token":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Bot identity fields are schema-validated and suppressed."},
	"huggingface-token":         {Status: VerificationAuditReviewed, Batch: 1, Notes: "Currently issued hf_ tokens use a schema-validated whoami contract with suppressed identity metadata."},
	"groq-api-key":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "OpenAI-compatible model-list response is schema-validated."},
	"replicate-token":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "The documented 40-character token format and account identity response are validated."},
	"airtable-pat":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "Whoami identity is schema-validated and suppressed."},
	"asana-pat":                 {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-user data.gid is schema-validated and suppressed."},
	"clickup-token":             {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-user identity is schema-validated and suppressed."},
	"typeform-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Preserve structured authentication errors and validate user identity."},
	"hubspot-private-app-token": {Status: VerificationAuditReviewed, Batch: 1, Notes: "Daily private-app usage is schema-validated; scope, migration, and provider failures remain unknown."},
	"mailchimp-key":             {Status: VerificationAuditReviewed, Batch: 1, Notes: "The data-center suffix and account-neutral ping response are validated and suppressed."},
	"klaviyo-key":               {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Replace profile lookup with bounded account metadata."},
	"iterable-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Resolve key type and region ambiguity before classifying rejection."},
	"nightfall-api-key":         {Status: VerificationAuditReviewed, Batch: 1, Notes: "Read-only detection-rules collection is validated and suppressed."},
	"pinecone-api-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "Control-plane index collection is schema-validated and suppressed."},
	"elevenlabs-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "User identity response is schema-validated and suppressed."},
	"xai-api-key":               {Status: VerificationAuditReviewed, Batch: 1, Notes: "The documented API-key identity endpoint validates key state and suppresses identity and ACL metadata."},
	"cohere-api-key":            {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated; context-sensitive rejection remains unknown."},
	"mistral-api-key":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated; hosted-key rejection remains unknown."},
	"togetherai-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Top-level model-list response is schema-validated and suppressed."},
	"fireworksai-api-key":       {Status: VerificationAuditReviewed, Batch: 1, Notes: "Bounded model response is schema-validated and suppressed."},
	"voyageai-api-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "The bounded file-list envelope is validated and file metadata are suppressed."},
	"perplexity-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Router model-list response is schema-validated and suppressed."},
	"openrouter-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Uses the documented key endpoint with nested data validation."},
	"ai21-api-key":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "One-file library list requires HTTP 200 and typed file identity; empty arrays accepted, errors remain unknown and file metadata suppressed."},
	"cerebras-api-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated and forbidden responses remain ambiguous."},
	"baseten-api-key":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Uses bearer management authentication with model-list validation."},
	"runpod-api-key":            {Status: VerificationAuditReviewed, Batch: 1, Notes: "Uses the documented REST v1 pods collection with identity/status schema validation and response suppression; ambiguous authorization remains unknown."},
	"fal-ai-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Prove authenticated model-list semantics and validate key boundaries."},
	"novita-api-key":            {Status: VerificationAuditReviewed, Batch: 1, Notes: "Replaced the public model list with authenticated billing balance metadata; numeric-string schema is validated and financial data suppressed. Inference error strings do not classify billing rejection."},
	"zilliz-api-key":            {Status: VerificationAuditReviewed, Batch: 1, Notes: "HTTP 200 requires explicit numeric zero code and typed project collection; missing codes and unproven application errors stay unknown, metadata suppressed."},
	"chroma-cloud-api-key":      {Status: VerificationAuditReviewed, Batch: 1, Notes: "Cloud identity requires user, tenant and typed database list; authorization-only regional fallback and response suppression."},
	"harness-pat":               {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate SaaS current-user response while preserving self-managed ambiguity."},
	"zoho-crm-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate user response and bounded regional fallback."},
	"intercom-access-token":     {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-admin type and string identity are validated and suppressed; fixed-region fallback occurs only for authorization ambiguity."},
	"front-api-token":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "The broad opaque-token fallback was removed; company identity is schema-validated and suppressed."},
	"segment-api-key":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "The legacy Config API workspace collection is schema-validated and suppressed."},
	"posthog-personal-api-key":  {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-user UUID/email validated and suppressed; bounded US/EU fallback preserves self-hosted and scope ambiguity."},
	"launchdarkly-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "Caller account and authentication-kind fields are validated and suppressed; SDK keys remain locally unsupported and deployment fallback is bounded."},
	"postmark-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Route server and account token variants independently."},

	"coda-api-token":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Whoami user and workspace identity fields are schema-validated and suppressed."},
	"calendly-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "Current-user resource identity and realistic OAuth JWT boundaries are validated with profile suppression."},
	"monday-api-token":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only me query requires an identity at data.me.id with no GraphQL errors; profile and error metadata are suppressed."},
	"flyio-token":                        {Status: VerificationAuditReviewed, Batch: 2, Notes: "Current fm2 token headers use the dedicated cryptographic authentication endpoint with suppressed token metadata."},
	"cloudflare-ca-key":                  {Status: VerificationAuditBlocked, Batch: 2, Notes: "Cloudflare Origin CA service keys retire on 2026-09-30."},
	"azure-app-config-connection-string": {Status: VerificationAuditReviewed, Batch: 2, Notes: "Signed read-only App Configuration request is context-complete and suppressed."},
	"azure-storage-connection-string":    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Signed bounded Azure Storage list request is context-complete and suppressed."},
	"spectralops-token":                  {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only user collection contract is bounded and suppressed."},
	"atlassian-api-token":                {Status: VerificationAuditReviewed, Batch: 2, Notes: "A single organization page is validated by collection and org identity/type; metadata are suppressed and admin-key subtype or permission ambiguity remains unknown."},
	"salesforce-access-token":            {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate userinfo and preserve production or sandbox endpoint ambiguity."},
	"openphone-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded users response and provider rename contract."},
	"dialpad-api-key":                    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Company identity accepts documented string/numeric IDs; production/sandbox fallback is authorization-only, with restricted-key ambiguity and metadata suppression."},
	"ringover-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only user collection is schema-classified and suppressed."},
	"callrail-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "The one-account page and token authorization contract are validated and suppressed."},
	"mailjet-basic-auth":                 {Status: VerificationAuditReviewed, Batch: 2, Notes: "Credential parsing and bounded message request are validated and suppressed."},
	"urlscan-api-key":                    {Status: VerificationAuditReviewed, Batch: 2, Notes: "The current authenticated quota scope is schema-validated and suppressed."},
	"deepseek-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "Model-list success and insufficient-balance authentication are classified with suppressed responses."},
	"weightsandbiases-api-key":           {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only viewer query requires string identity without GraphQL errors; null viewer and self-hosted ambiguity stay unknown, profile suppressed."},
	"assemblyai-api-key":                 {Status: VerificationAuditReviewed, Batch: 2, Notes: "One-transcript page validates IDs, statuses and result count; authorization-only regional fallback and response suppression."},
	"deepgram-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "The projects envelope and structured permission errors are validated with project metadata suppression."},
	"contentful-pat":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "One-space page validates collection and space system types; permission failures stay unknown and regional fallback is bounded."},
	"storyblok-personal-access-token":    {Status: VerificationAuditReviewed, Batch: 2, Notes: "One-space management page validates IDs and names; fixed-region authorization-only fallback suppresses metadata."},
	"storyblok-access-token":             {Status: VerificationAuditReviewed, Batch: 2, Notes: "Current-space ID and name validated and suppressed; fixed-region authorization-only fallback and documented token query authentication."},
	"sanity-auth-token":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Resolve personal and robot token endpoint compatibility."},
	"datocms-api-token":                  {Status: VerificationAuditReviewed, Batch: 2, Notes: "Metered CMA site identity and JSON:API errors are schema-classified and suppressed behind unsafe opt-in."},
	"elastic-email-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Replace sensitive key listing with bounded account identity."},
	"webflow-api-key":                    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Documented token introspection requires authorization and application identity; site-token/scope ambiguity remains unknown and returned authorization metadata are suppressed."},
	"mapbox-secret-token":                {Status: VerificationAuditReviewed, Batch: 2, Notes: "Three-part secret tokens use typed token inspection with suppressed authorization metadata."},
	"locationiq-api-key":                 {Status: VerificationAuditReviewed, Batch: 2, Notes: "Balance requires ok status and numeric day/bonus credits; bounded regional fallback, scope ambiguity preserved and balances suppressed."},
	"coinapi-key":                        {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate limits response and suppress quota metadata."},
	"onfido-api-token":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded applicant collection and suppress PII."},
	"unit-api-token":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Bounded account collection is schema-classified and suppressed."},
	"increase-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API credentials from webhook and OAuth secrets."},
	"lithic-api-key":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Bounded account-holder collection is schema-classified and suppressed."},
	"persona-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API tokens from webhook secrets and suppress inquiry PII."},
	"apisports-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress subscription response and narrow invalid markers."},
	"opticodds-api-key":                  {Status: VerificationAuditReviewed, Batch: 2, Notes: "Static sports collection is schema-classified and suppressed."},
	"complyadvantage-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Replace unbounded regional user lists with a bounded contract."},
	"bitgo-access-token":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Confirm test host and validate user identity."},
	"circle-api-key":                     {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API keys from webhook secrets and support sandbox context."},
	"trulioo-api-key":                    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Dedicated authentication endpoint is schema-classified and suppressed."},
	"etherscan-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress quota-bearing chain response and test provider error codes."},
	"guardian-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded search response and suppress article metadata."},
	"sourcegraph-token":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress cloud identity and preserve local token no-request behavior."},
	"sourcegraph-cody-token":             {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate limits response and preserve forbidden ambiguity."},
	"snyk-api-key":                       {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate regional self response and cap fallback requests."},
	"uptimerobot-api-key":                {Status: VerificationAuditReviewed, Batch: 2, Notes: "The bounded monitor envelope and API-key application error are classified and suppressed."},
	"statuspage-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Bound or replace page collection and confirm authorization form."},
	"sendinblue-api-key":                 {Status: VerificationAuditReviewed, Batch: 2, Notes: "Account identity is schema-validated and plan, address, and relay metadata are suppressed."},
	"teamwork-token":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Launchpad identity response is schema-classified and suppressed."},

	"salesblink-api-key":                  {Status: VerificationAuditBlocked, Batch: 3, Notes: "No authoritative provider verification contract or error schema is available."},
	"mailmodo-api-key":                    {Status: VerificationAuditBlocked, Batch: 3, Notes: "No documented bounded verification endpoint or response contract is available."},
	"triggerdev-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Narrow supported key variants and validate the top-level run-list schema."},
	"resend-api-key":                      {Status: VerificationAuditReviewed, Batch: 3, Notes: "Current key boundaries, bounded list schema, and structured restricted-key states are validated and suppressed."},
	"clerk-secret-key":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Replace the deprecated clients probe with a current bounded endpoint."},
	"workos-api-key":                      {Status: VerificationAuditReviewed, Batch: 3, Notes: "The bounded organization-list envelope and restricted-key response are classified and suppressed."},
	"liveblocks-secret-key":               {Status: VerificationAuditReviewed, Batch: 3, Notes: "The bounded room-list envelope and structured key errors are validated with room metadata suppression."},
	"polar-access-token":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve production and sandbox routing and validate organization responses."},
	"temporal-cloud-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split API keys from client secrets and validate current identity."},
	"trayio-api-token":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve token families and regional hosts before promotion."},
	"airbyte-api-token":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "Cloud, self-managed, and client-secret credential contexts are conflated."},
	"hightouch-api-key":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "The current workspace endpoint lacks a public provider-owned contract."},
	"deno-deploy-token":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "The implemented organization collection route is absent from the current API contract."},
	"supabase-management-token":           {Status: VerificationAuditReviewed, Batch: 3, Notes: "Cloud project collection is schema-validated and suppressed."},
	"prefect-api-key":                     {Status: VerificationAuditReviewed, Batch: 3, Notes: "Cloud workspace collection is schema-validated and suppressed."},
	"figma-pat":                           {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split personal tokens from OAuth variants and validate current-user identity."},
	"saladcloud-api-key":                  {Status: VerificationAuditBlocked, Batch: 3, Notes: "Safe reads require organization context that the detector does not capture."},
	"neon-api-key":                        {Status: VerificationAuditReviewed, Batch: 3, Notes: "Dedicated authentication response is schema-validated and suppressed."},
	"turso-api-token":                     {Status: VerificationAuditReviewed, Batch: 3, Notes: "Organization collection is schema-validated and suppressed."},
	"xata-api-key":                        {Status: VerificationAuditReviewed, Batch: 3, Notes: "Organization collection is schema-validated and suppressed."},
	"cockroachcloud-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Narrow credential context and validate the cluster-list schema."},
	"motherduck-token":                    {Status: VerificationAuditReviewed, Batch: 3, Notes: "Preview active-account schema and both documented and live authentication error families are classified and suppressed."},
	"singlestore-api-key":                 {Status: VerificationAuditReviewed, Batch: 3, Notes: "Current organization orgID/name validated; existing hex-key no-request gate retained, allowlist failures unknown and metadata suppressed."},
	"gcp-service-account-json":            {Status: VerificationAuditReviewed, Batch: 3, Notes: "Signed read-only token exchange is schema-classified and suppressed."},
	"gcp-application-default-credentials": {Status: VerificationAuditReviewed, Batch: 3, Notes: "Authorized-user token exchange is schema-classified and suppressed."},
	"closecrm-api-key":                    {Status: VerificationAuditReviewed, Batch: 3, Notes: "A minimal current-user ID response is validated; broad account restrictions remain unknown."},
	"paystack-secret-key":                 {Status: VerificationAuditReviewed, Batch: 3, Notes: "Balance response requires status=true and typed currency/balance entries; financial data are suppressed and unproven rejection remains unknown."},
	"wrike-access-token":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Harden token format, regional fallback, and current-contact schema."},
	"flutterwave-secret-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Support current key variants and suppress validated balance data."},
	"pagarme-live-key":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split current and legacy key formats before endpoint verification."},
	"rechargepayments-token":              {Status: VerificationAuditReviewed, Batch: 3, Notes: "The scope-free token-information contract validates identity and reports restricted tokens without store metadata."},
	"lemonsqueezy-api-token":              {Status: VerificationAuditReviewed, Batch: 3, Notes: "JWT boundaries and JSON:API user identity are validated with suppressed account metadata."},
	"cloudinary-url":                      {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Correlate cloud identity and suppress validated configuration data."},
	"helpcrunch-api-key":                  {Status: VerificationAuditReviewed, Batch: 3, Notes: "Department collection and structured rejection are schema-classified and suppressed."},
	"line-messaging-token":                {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve channel-token variants and validate bot identity."},
	"courier-api-key":                     {Status: VerificationAuditReviewed, Batch: 3, Notes: "Current published keys use the preference-sections schema with gateway and authorization errors distinguished."},
	"virustotal-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Parse structured errors, validate sentinel identity, and suppress metadata."},
	"shodan-api-key":                      {Status: VerificationAuditReviewed, Batch: 3, Notes: "API-info plan and capability fields are validated with quota suppression."},
	"securitytrails-api-key":              {Status: VerificationAuditReviewed, Batch: 3, Notes: "Dedicated ping response is schema-classified and suppressed."},
	"newsapi-key":                         {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate article-list schema and structured key status errors."},
	"openweather-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Schema-classify weather responses and account for quota-bearing workload."},
	"tomorrowio-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Harden key format, response schema, and quota-bearing workload handling."},
	"here-api-key":                        {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate geocode results and preserve feature-restriction ambiguity."},
	"polygon-api-key":                     {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Update provider routing and avoid quota-bearing ticker lookup."},
	"scaleway-secret-key":                 {Status: VerificationAuditBlocked, Batch: 3, Notes: "Project verification requires organization and access-key context."},
	"braintree-access-token":              {Status: VerificationAuditReviewed, Batch: 3, Notes: "Environment-routed GraphQL ping and error classes are schema-classified and suppressed."},
	"webex-access-token":                  {Status: VerificationAuditReviewed, Batch: 3, Notes: "Current-user identity is schema-validated and suppressed."},
	"detectify-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split V2 and V3 credential formats and endpoint contracts."},
	"twitter-bearer-token":                {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Replace the billable post lookup with a bounded account endpoint."},
	"twitch-access-token":                 {Status: VerificationAuditReviewed, Batch: 3, Notes: "The dedicated token-introspection schema is validated and identity and scope data are suppressed."},

	"ipinfo-token":                    {Status: VerificationAuditReviewed, Batch: 4, Notes: "Unlimited Lite identity lookup is schema-validated and suppressed."},
	"coinlayer-api-key":               {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota and may incur overage charges."},
	"cryptocompare-api-key":           {Status: VerificationAuditBlocked, Batch: 4, Notes: "The legacy endpoint and key contract are absent from current provider documentation."},
	"worldcoinindex-api-key":          {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes a scarce hourly request quota."},
	"fixerio-api-key":                 {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"currencylayer-api-key":           {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"exchangerate-api-key":            {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe quota verification itself consumes provider request quota."},
	"exchangeratesapi-api-key":        {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"currencyfreaks-api-key":          {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes a hard monthly request quota."},
	"currencyscoop-api-key":           {Status: VerificationAuditBlocked, Batch: 4, Notes: "Legacy CurrencyScoop keys are not proven compatible with CurrencyBeacon."},
	"fastforex-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Move to a bounded usage contract and correct documented key boundaries."},
	"marketstack-api-key":             {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes quota with automatic paid overages."},
	"financialmodelingprep-api-key":   {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe exchange lookup consumes provider request quota."},
	"finnhub-api-key":                 {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe quote lookup consumes provider request quota."},
	"tradier-token":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Correct token boundaries, support sandbox context, and suppress profile data."},
	"twelvedata-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Suppress account usage data and document one-credit verification workload."},
	"vatlayer-api-key":                {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification may incur automatic per-request overages."},
	"worldweather-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Resolve key boundaries and validate and suppress weather responses."},
	"positionstack-api-key":           {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe geocoding verification may incur automatic overages."},
	"geocodio-api-key":                {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification performs a billable geocoding lookup."},
	"telnyx-api-key":                  {Status: VerificationAuditReviewed, Batch: 4, Notes: "Balance identity and structured authentication codes are validated with financial suppression."},
	"vagrant-cloud-token":             {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Suppress authentication response and account for scheduled service shutdown."},
	"zeplin-token":                    {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Separate personal tokens from OAuth variants and suppress current-user data."},
	"vultr-api-key":                   {Status: VerificationAuditReviewed, Batch: 4, Notes: "Nested account name/email are validated and suppressed; ACL and IP-restriction failures remain unknown."},
	"airbrake-user-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate bounded project collection and suppress project metadata."},
	"infura-project-id":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Use the lowest-cost RPC probe and preserve endpoint-security ambiguity."},
	"messagebird-api-key":             {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Correct live and test key variants and suppress validated balance data."},
	"pinata-jwt":                      {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated authentication response is schema-validated and suppressed."},
	"pushbullet-token":                {Status: VerificationAuditReviewed, Batch: 4, Notes: "Detected prefixed tokens use a schema-validated current-user request with suppressed profile data."},
	"stormglass-api-key":              {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe weather verification consumes scarce metered requests."},
	"bunny-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace undocumented endpoint and split account, Stream, and storage credentials."},
	"imgix-api-token":                 {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split API and secure URL tokens and suppress source metadata."},
	"keycdn-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace the unbounded sensitive zone listing with a bounded contract."},
	"eventbrite-private-token":        {Status: VerificationAuditReviewed, Batch: 4, Notes: "Current-user identifier and name are validated and suppressed; unproven authorization failures remain unknown."},
	"harvest-access-token":            {Status: VerificationAuditReviewed, Batch: 4, Notes: "Identity and accessible-account schemas are validated with a compliant User-Agent and full response suppression."},
	"lokalise-token":                  {Status: VerificationAuditReviewed, Batch: 4, Notes: "The bounded projects collection and current invalid-header response are classified and suppressed."},
	"nylas-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split API keys from client secrets and correlate regional context."},
	"pipedream-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Narrow credential types and validate and suppress current-user identity."},
	"percy-token":                     {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Distinguish public fallback and token permissions before promotion."},
	"crowdin-token":                   {Status: VerificationAuditBlocked, Batch: 4, Notes: "Crowdin.com and organization-specific Enterprise hosts are unresolved."},
	"sendbird-organization-api-token": {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace application listing because it returns additional API tokens."},
	"checkly-api-key":                 {Status: VerificationAuditBlocked, Batch: 4, Notes: "Verification requires account context not captured by the detector."},
	"incidentio-api-key":              {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated identity response is schema-validated and suppressed."},
	"firehydrant-api-key":             {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated ping response is schema-validated and suppressed."},
	"ilert-api-key":                   {Status: VerificationAuditReviewed, Batch: 4, Notes: "Current-user identity is schema-validated and suppressed."},
	"semgrep-app-token":               {Status: VerificationAuditReviewed, Batch: 4, Notes: "Deployment collection is schema-validated and suppressed."},
	"socketdev-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate organizations, suppress metadata, and account for request quota."},
	"cronitor-api-key":                {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split telemetry-only and resource-scoped keys before bounded reads."},
	"gocardless-access-token":         {Status: VerificationAuditReviewed, Batch: 4, Notes: "Environment-specific creditor collection is schema-validated and suppressed."},
	"gumroad-access-token":            {Status: VerificationAuditReviewed, Batch: 4, Notes: "Seller identity response is schema-validated and suppressed."},

	"hellosign-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dropbox Sign account identity is schema-validated and suppressed."},
	"mailboxlayer-api-key":   {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe email validation consumes metered quota with automatic overages."},
	"mediastack-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe news lookup consumes metered quota with automatic overages."},
	"opencage-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding consumes request allowance and may incur charges."},
	"packagecloud-token":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded repository collection is schema-validated and suppressed."},
	"phrase-access-token":    {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Split legacy and Platform token families and validate regional current-user identity."},
	"semaphore-api-token":    {Status: VerificationAuditBlocked, Batch: 5, Notes: "Current API requires organization context absent from the detector."},
	"scrutinizer-token":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Bound repository pagination and validate the embedded collection envelope."},
	"openuv-api-key":         {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe live UV calculation consumes provider workload."},
	"pandascore-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe static-data lookup consumes hourly request allowance."},
	"paperform-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded forms collection is schema-validated and suppressed."},
	"parsehub-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "The one-project envelope is schema-validated and private project metadata are suppressed."},
	"pdfshift-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Adopt current X-API-Key credentials and validate credits usage."},
	"peopledatalabs-api-key": {Status: VerificationAuditReviewed, Batch: 5, Notes: "Parameterless authentication probe uses structured errors and cannot produce a billable match."},
	"scrapingbee-api-key":    {Status: VerificationAuditBlocked, Batch: 5, Notes: "The usage route lacks a current public provider contract."},
	"serpstack-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe live SERP lookup consumes metered quota with automatic overages."},
	"shotstack-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate nested template-list responses across stage and production."},
	"abstract-api-key":       {Status: VerificationAuditBlocked, Batch: 5, Notes: "Product-specific Abstract keys cannot be validated against one generic endpoint."},
	"alchemy-api-key":        {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe RPC verification consumes billed compute units."},
	"apilayer-key":           {Status: VerificationAuditBlocked, Batch: 5, Notes: "Generic marketplace keys lack subscribed-product context."},
	"bannerbear-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Separate V2 keys and validate and suppress account metadata."},
	"baremetrics-api-key":    {Status: VerificationAuditReviewed, Batch: 5, Notes: "Nested account identifier and company are validated; account and financial metadata are suppressed."},
	"beamer-api-key":         {Status: VerificationAuditReviewed, Batch: 5, Notes: "Read-only configured URL response is schema-validated and suppressed."},
	"bitbar-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Establish current identity schema and suppress user metadata."},
	"blazemeter-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Narrow API Monitoring tokens and validate account identity."},
	"buttercms-api-token":    {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe content lookup consumes metered usage with paid overages."},
	"canny-api-key":          {Status: VerificationAuditBlocked, Batch: 5, Notes: "Board listing is unbounded and retrieves private-board token material."},
	"chartmogul-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dedicated ping response is schema-validated and suppressed."},
	"clearbit-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe enrichment lookup consumes quota and processes personal data."},
	"clockify-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Global current-user string identity/email are validated and suppressed; region/subdomain context failures remain unknown."},
	"cloudconvert-api-key":   {Status: VerificationAuditReviewed, Batch: 5, Notes: "Production current-user ID, username and email validated and suppressed; scope and sandbox ambiguity remain unknown."},
	"convertapi-secret":      {Status: VerificationAuditBlocked, Batch: 5, Notes: "Detected secret format is not mapped to the Master Token accepted by the endpoint."},
	"convertkit-api-secret":  {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate the deprecated V3 account schema and suppress account metadata."},
	"dailyco-api-key":        {Status: VerificationAuditReviewed, Batch: 5, Notes: "Domain identity/config replaces room listing; permission failures stay unknown and configuration data are suppressed."},
	"fullstory-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dedicated authentication role response is schema-validated and suppressed."},
	"flagsmith-server-key":   {Status: VerificationAuditBlocked, Batch: 5, Notes: "Client and server keys plus self-hosted API bases are conflated."},
	"growthbook-api-key":     {Status: VerificationAuditBlocked, Batch: 5, Notes: "Cloud and self-hosted secret keys require endpoint context."},
	"configcat-sdk-key":      {Status: VerificationAuditBlocked, Batch: 5, Notes: "Config download is metered and deployment or CDN context is unresolved."},
	"pendo-integration-key":  {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Correlate regional host and validate and suppress metadata schema."},
	"kustomer-api-token":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Current-user identity is schema-validated and suppressed."},
	"productboard-api-token": {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Bound member listing and validate and suppress member data."},
	"planhat-api-token":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded user collection is schema-validated and suppressed."},
	"geoapify-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding lookup consumes provider credits."},
	"graphhopper-api-key":    {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding lookup consumes provider credits."},
	"hunter-api-key":         {Status: VerificationAuditReviewed, Batch: 5, Notes: "Free authenticated account lookup validates email and plan; header authentication retained and account/quota metadata suppressed."},
	"imagekit-private-key":   {Status: VerificationAuditReviewed, Batch: 5, Notes: "One-file list explicitly requests file type; array entries require fileId/name and metadata are suppressed."},
	"kickbox-api-key":        {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe email validation consumes credits and may trigger auto-recharge."},
	"klipfolio-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Require successful top-level metadata and test structured errors."},
	"lob-api-key":            {Status: VerificationAuditReviewed, Batch: 5, Notes: "One-address list validates list/address resource types and IDs; address PII suppressed and permission failures unknown."},
	"moosend-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Establish current response and error fixtures before promotion."},

	"numverify-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe phone validation consumes metered quota and may incur overages."},
	"omnisend-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Current-brand identity is schema-validated and suppressed."},
	"pandadoc-api-key":            {Status: VerificationAuditBlocked, Batch: 6, Notes: "No current bounded identity endpoint is documented."},
	"partnerstack-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Split Partner and Vendor credentials and bound partnership reads."},
	"paymongo-secret-key":         {Status: VerificationAuditBlocked, Batch: 6, Notes: "Webhook listing retrieves additional signing secrets."},
	"photoroom-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Non-processing account usage response is schema-validated and suppressed."},
	"qase-api-token":              {Status: VerificationAuditReviewed, Batch: 6, Notes: "One-project page requires status=true and typed project entities; Enterprise host ambiguity remains unknown and metadata suppressed."},
	"replyio-api-key":             {Status: VerificationAuditReviewed, Batch: 6, Notes: "The current whoami endpoint validates team keys and classifies organization-key context without contact enumeration."},
	"restpack-htmltopdf-api-key":  {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress the non-rendering usage response."},
	"restpack-screenshot-api-key": {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Require the complete usage schema and preserve subscription ambiguity."},
	"rocketreach-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Account identity and state are validated with credit and PII suppression."},
	"route4me-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Replace or strictly bound address-book verification."},
	"salesflare-api-key":          {Status: VerificationAuditReviewed, Batch: 6, Notes: "Current-user identity replaces contact listing and all profile and billing metadata are suppressed."},
	"attio-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Token introspection is schema-classified and suppressed."},
	"affinity-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Whoami identity and grant are schema-validated and suppressed."},
	"salesloft-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Documented ak_ API keys use a schema-validated current-user response with PII suppression."},
	"instantly-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Bounded current-workspace response is schema-classified and suppressed."},
	"smartlead-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Replace unbounded campaign listing with a bounded contract."},
	"greenhouse-harvest-api-key":  {Status: VerificationAuditBlocked, Batch: 6, Notes: "Legacy Harvest verification is retired and v3 requires OAuth context."},
	"ashby-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Dedicated API-key identity response is schema-validated and suppressed."},
	"workable-api-token":          {Status: VerificationAuditReviewed, Batch: 6, Notes: "The accounts collection is schema-validated and explicit invalid-token signals are separated from scope ambiguity."},
	"smartrecruiters-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Separate SmartToken and OAuth contracts before identity verification."},
	"deel-api-token":              {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe contract read retrieves sensitive HR records across unresolved environments."},
	"gusto-api-token":             {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Separate environments and credential types before token introspection."},
	"airvisual-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe environmental lookup consumes metered workload."},
	"ambee-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe air-quality lookup consumes metered workload."},
	"apiflash-access-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "The non-rendering quota endpoint is schema-validated and billing metadata are suppressed."},
	"apitemplate-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Read-only template collection is schema-classified and suppressed."},
	"appfollow-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe account-user read consumes provider API credits."},
	"autoklose-api-key":           {Status: VerificationAuditBlocked, Batch: 6, Notes: "The implemented endpoint redirects and no current API contract is documented."},
	"aviationstack-api-key":       {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe flight lookup consumes metered quota with automatic overages."},
	"ayrshare-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress linked-account user profile metadata."},
	"besttime-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Dedicated private-key validation is schema-classified and suppressed."},
	"brandfetch-api-key":          {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe brand lookup consumes quota with automatic overages."},
	"browshot-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "The minimal account balance schema is validated and suppressed."},
	"calendarific-api-key":        {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe countries lookup consumes monthly request allowance."},
	"craftmypdf-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Correct account schema and padded key format before promotion."},
	"currentsapi-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe latest-news lookup consumes daily request quota."},
	"debounce-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe mailbox validation consumes a paid verification credit."},
	"detectlanguage-api-key":      {Status: VerificationAuditReviewed, Batch: 6, Notes: "Account-status authentication response is schema-validated and suppressed."},
	"codemagic-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Bound and validate app collection and suppress workflow metadata."},
	"diffbot-api-token":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Read-only account usage response is schema-classified and suppressed."},
	"ethplorer-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe blockchain lookup consumes provider request allowance."},
	"geckoboard-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Require exact authentication-ping schema and reconcile key format."},
	"holidayapi-key":              {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe countries lookup consumes monthly request allowance."},
	"ip2location-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe geolocation lookup consumes quota with automatic overages."},
	"ipapi-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe IP lookup consumes quota with paid overages."},
	"ipinfodb-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe IP-country lookup consumes provider workload."},
	"jotform-api-key":             {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate identity, suppress user data, and handle unsupported custom hosts."},
	"languagelayer-api-key":       {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe language-data lookup consumes quota with automatic overages."},

	"linkpreview-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe verification performs a metered remote-page crawl."},
	"mockaroo-api-key":         {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe metadata read consumes scarce request allowance."},
	"oanda-api-token":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "Account collection requires string IDs and no errorCode; practice/live fallback is authorization-only and account metadata suppressed."},
	"onfleet-api-key":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "The official dedicated authentication probe is status-classified and organization metadata are suppressed."},
	"pepipost-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Move legacy verification to documented regional Netcore V6."},
	"pivotaltracker-api-token": {Status: VerificationAuditBlocked, Batch: 7, Notes: "The current service and provider-owned API contract are unavailable."},
	"pixabay-api-key":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe media search consumes provider request allowance."},
	"podio-api-token":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "User status identity and structured OAuth errors are classified with HTTP 420 handling and response suppression."},
	"rawg-api-key":             {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe game-database lookup consumes metered requests."},
	"selectpdf-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Non-rendering subscription usage response is schema-validated and suppressed."},
	"shipday-api-key":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "Read-only carrier collection is schema-classified and suppressed."},
	"signable-api-key":         {Status: VerificationAuditBlocked, Batch: 7, Notes: "Authoritative workload, quota, and billing documentation is unavailable."},
	"signaturit-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Harden production and sandbox fallback before promotion."},
	"simplesat-api-key":        {Status: VerificationAuditBlocked, Batch: 7, Notes: "Authoritative endpoint, quota, and billing contract is unavailable."},
	"snipcart-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate documented paginated order envelope and suppress PII."},
	"spoonacular-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe recipe search consumes billable quota points."},
	"sportsmonk-api-token":     {Status: VerificationAuditReviewed, Batch: 7, Notes: "Bounded league response is schema-classified and suppressed."},
	"statuscake-api-key":       {Status: VerificationAuditReviewed, Batch: 7, Notes: "The one-monitor no-uptime envelope is schema-validated and suppressed."},
	"stockdata-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe quote lookup consumes daily request allowance."},
	"shippo-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress address collection and structured errors."},
	"easypost-api-key":         {Status: VerificationAuditReviewed, Batch: 7, Notes: "Provider-prefixed keys use bounded USPS service-level metadata with structured authentication errors."},
	"shipengine-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress regional account settings."},
	"aftership-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Current asat_ keys use a bounded USPS courier metadata contract with required headers and response suppression."},
	"easyship-api-token":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate account identity and suppress billing metadata."},
	"tatum-api-key":            {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe version probe consumes one provider credit."},
	"taxjar-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Correct token boundaries and validate static categories."},
	"tiingo-api-token":         {Status: VerificationAuditReviewed, Batch: 7, Notes: "Dedicated authentication response is schema-classified and suppressed."},
	"timecamp-api-token":       {Status: VerificationAuditReviewed, Batch: 7, Notes: "Current-user response is schema-classified and suppressed."},
	"toggltrack-api-token":     {Status: VerificationAuditReviewed, Batch: 7, Notes: "A related-data-disabled current-user response is schema-validated and suppressed."},
	"tomtom-api-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe raster-tile lookup consumes geospatial allowance."},
	"transferwise-api-token":   {Status: VerificationAuditReviewed, Batch: 7, Notes: "Versioned current-user ID/email validated and suppressed; production/sandbox fallback is authorization-only."},
	"unsplash-access-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe photo lookup consumes application request allowance."},
	"userstack-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe user-agent lookup consumes quota with paid overages."},
	"visualcrossing-api-key":   {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe weather lookup consumes record-metered workload."},
	"voicegain-api-key":        {Status: VerificationAuditBlocked, Batch: 7, Notes: "Cloud and Edge JWTs require deployment-specific endpoint context."},
	"yelp-api-key":             {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe business search is priced per API call."},
	"ynab-api-token":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Current-user identity replaces plan listing and structured account restrictions are classified and suppressed."},
	"zerobounce-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Use POST balance probe, suppress credits, and resolve regional routing."},
	"smartsheet-access-token":  {Status: VerificationAuditReviewed, Batch: 7, Notes: "Current-user ID and email validated with errorCode rejection; fixed-region fallback is authorization-only and profile data suppressed."},
	"thousandeyes-token":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Split OAuth and legacy credentials and preserve account-lockout ambiguity."},
	"ticketmaster-api-key":     {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe event search consumes daily API quota."},
	"theoddsapi-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Documented zero-quota sports catalog is array-validated and suppressed."},
	"teachable-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Bound and validate documented courses and metadata response."},
	"ubidots-token":            {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Confirm current identity endpoint and suppress user metadata."},
	"uclassify-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe classifier metadata consumes daily call allowance."},
	"upcdatabase-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Account endpoint avoids barcode quota and suppresses metadata."},
	"uplead-api-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Credits endpoint avoids enrichment billing and suppresses metadata."},
	"vbout-api-key":            {Status: VerificationAuditReviewed, Batch: 7, Notes: "The current top-level business identity schema replaces the incorrect legacy success contract."},
	"veriphone-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Non-validation credits response is schema-classified and suppressed."},
	"walkscore-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe walkability lookup consumes daily quota."},

	"whoxy-api-key":         {Status: VerificationAuditReviewed, Batch: 8, Notes: "Non-lookup account balance response is schema-classified and suppressed."},
	"wistia-api-token":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Move to modern token identity endpoint and suppress output."},
	"wit-ai-token":          {Status: VerificationAuditBlocked, Batch: 8, Notes: "No current provider-owned verification contract is available."},
	"ticket-tailor-api-key": {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Replace order retrieval with lower-sensitivity box-office metadata."},
	"tmetric-api-token":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "Current-user identity is schema-validated and all workspace and profile metadata are suppressed."},
	"signupgenius-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe profile verification consumes limited daily API allowance."},
	"skrapp-api-key":        {Status: VerificationAuditReviewed, Batch: 8, Notes: "Free account-credit response is schema-classified and suppressed."},
	"sslmate-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Separate product credential families and parse structured errors."},
	"storecove-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate experimental country-specification response."},
	"stormboard-api-key":    {Status: VerificationAuditBlocked, Batch: 8, Notes: "Implemented profile route lacks a current provider contract."},
	"streak-api-key":        {Status: VerificationAuditReviewed, Batch: 8, Notes: "Canonical current-user identity and Basic authentication are validated with profile suppression."},
	"abyssale-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Dedicated no-body authentication probe is schema-classified and suppressed."},
	"adafruit-io-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Confirm current-user contract and split modern and legacy key variants."},
	"alconost-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Confirm canonical Nitro host and current account schema."},
	"aletheia-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe financial-data lookup consumes monthly allowance."},
	"allsports-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe countries lookup consumes scarce hourly allowance."},
	"apacta-api-key":        {Status: VerificationAuditBlocked, Batch: 8, Notes: "Current endpoint, auth, pagination, and error contract are unavailable."},
	"api2cart-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe cart listing consumes paid request allowance."},
	"apimatic-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Bound generation listing and validate current response schema."},
	"apimetrics-api-key":    {Status: VerificationAuditReviewed, Batch: 8, Notes: "Bounded API-call collection is schema-classified and suppressed."},
	"appointedd-api-key":    {Status: VerificationAuditBlocked, Batch: 8, Notes: "Implemented availability route is absent from the current API contract."},
	"atera-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate and suppress bounded agent response."},
	"autopilot-api-key":     {Status: VerificationAuditBlocked, Batch: 8, Notes: "Only a legacy contract is available; current semantics are unresolved."},
	"axonaut-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Apply documented pagination and validate private company collection."},
	"beebole-api-token":     {Status: VerificationAuditBlocked, Batch: 8, Notes: "No authoritative current custom_field.list contract is available."},
	"bombbomb-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate current-user identity and structured errors."},
	"borgbase-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Read-only GraphQL repository-ID query is schema-classified and suppressed."},
	"buddyns-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Documented user identity endpoint is schema-classified and suppressed."},
	"bugherd-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe project listing retrieves additional project API keys."},
	"caflou-api-key":        {Status: VerificationAuditBlocked, Batch: 8, Notes: "No authoritative account-list pagination or schema contract is available."},
	"calorieninja-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe nutrition enrichment consumes product workload."},
	"captaindata-api-key":   {Status: VerificationAuditReviewed, Batch: 8, Notes: "The no-credit-cost quota identity is schema-validated and billing metadata are suppressed."},
	"chatbot-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Read-only story collection is schema-classified and suppressed."},
	"cliengo-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Migrate legacy UUID query credentials to current Bearer tokens."},
	"avaza-api-token":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Account response is schema-classified and suppressed."},
	"cloudplan-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Establish current account schema and suppress response."},
	"cloverly-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Establish a current account endpoint and error contract."},
	"clustdoc-api-key":      {Status: VerificationAuditBlocked, Batch: 8, Notes: "Current route resolves to an HTML login flow."},
	"codequiry-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "The dedicated auth-validation endpoint replaces check history and suppresses account identity."},
	"column-api-key":        {Status: VerificationAuditReviewed, Batch: 8, Notes: "Bounded entity collection is schema-classified and suppressed."},
	"commodities-api-key":   {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe public-symbol lookup consumes metered request quota."},
	"countrylayer-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe country-data lookup consumes metered request quota."},
	"dandelion-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe NLP language detection consumes processing units."},
	"datagov-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Replace retired endpoint with a live bounded participating-agency contract."},
	"diggernaut-api-key":    {Status: VerificationAuditReviewed, Batch: 8, Notes: "Documented project collection is schema-classified and suppressed."},
	"docparser-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "The documented Basic-auth ping replaces parser listing and query-string credentials."},
	"dynalist-api-token":    {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Suppress private file-list metadata and harden application errors."},
	"dyspatch-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "The current media version and typed template cursor envelope are validated and suppressed."},
	"envoy-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate locations schema and confirm key format and media version."},
	"everhour-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Version-pinned current-user identity is validated while ambiguous access denial remains unknown."},

	"feedier-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Move to a current documented bounded v3 resource."},
	"finage-api-key":        {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe financial-data lookup consumes product workload."},
	"flatio-api-key":        {Status: VerificationAuditReviewed, Batch: 9, Notes: "Current-user required fields and structured invalid, scope, and rate-limit errors are classified and suppressed."},
	"flexport-api-key":      {Status: VerificationAuditBlocked, Batch: 9, Notes: "Detected key format is not tied to a current documented endpoint."},
	"flickr-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Suppress echoed key material and tighten application-key boundaries."},
	"flightapi-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe travel-data lookup consumes API credits."},
	"float-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace private people listing with a lower-sensitivity account read."},
	"frameio-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Split legacy and Adobe IMS token contracts and suppress identity."},
	"fulcrum-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correlate regional host and validate private user collection."},
	"geocodify-api-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe forward geocoding consumes monthly quota."},
	"getgeoapi-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe currency-list lookup consumes daily allowance."},
	"glassnode-api-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "Credit-free metadata collection is array-validated and suppressed."},
	"goodday-api-key":       {Status: VerificationAuditBlocked, Batch: 9, Notes: "Authoritative pagination, quota, and error contracts are unavailable."},
	"groovehq-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy current-user identity is schema-validated and suppressed."},
	"gtmetrix-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Non-testing account-status response is schema-classified and suppressed."},
	"gyazo-api-token":       {Status: VerificationAuditBlocked, Batch: 9, Notes: "Current provider-owned identity endpoint contract is unavailable."},
	"happyscribe-api-key":   {Status: VerificationAuditBlocked, Batch: 9, Notes: "Private transcription listing lacks an authoritative bounded contract."},
	"humanity-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Bearer-authenticated current-user ID and the specific application-level invalid-token response are classified and suppressed."},
	"hybiscus-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Quota-period identity and exact invalid-key details are validated and suppressed."},
	"ibmcloud-user-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "IAM token exchange is schema-classified and suppressed."},
	"iconfinder-api-key":    {Status: VerificationAuditReviewed, Batch: 9, Notes: "Bounded iconset collection is schema-classified and suppressed."},
	"insightly-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correlate pod context and preserve daily-quota ambiguity."},
	"interseller-api-key":   {Status: VerificationAuditBlocked, Batch: 9, Notes: "Provider service sunsets on December 15, 2026."},
	"intrinio-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress account identity and usage metadata."},
	"juro-api-key":          {Status: VerificationAuditReviewed, Batch: 9, Notes: "Template collection is schema-classified and suppressed."},
	"knapsackpro-api-token": {Status: VerificationAuditReviewed, Batch: 9, Notes: "Build collection read is schema-classified and suppressed."},
	"kylas-api-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Bounded contact response is schema-classified and suppressed."},
	"leadfeeder-api-key":    {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy account collection is schema-classified and suppressed."},
	"livestorm-api-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "The dedicated ping accepts documented empty success and classifies authentication and workspace statuses."},
	"loadmill-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "The current unfiltered teamLabels schema replaces legacy filter and media-version assumptions."},
	"loyverse-api-token":    {Status: VerificationAuditReviewed, Batch: 9, Notes: "Merchant UUID and structured inactive, invalid, and scope-restricted states are classified and suppressed."},
	"lunchmoney-api-token":  {Status: VerificationAuditReviewed, Batch: 9, Notes: "The complete v2 current-user contract and documented invalid-token envelope are validated and suppressed."},
	"madkudu-api-key":       {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy no-workload authentication ping is schema-classified and suppressed."},
	"mailjetsms-api-token":  {Status: VerificationAuditBlocked, Batch: 9, Notes: "Implemented SMS route lacks a current verification contract."},
	"mailsac-api-key":       {Status: VerificationAuditReviewed, Batch: 9, Notes: "Current k_ keys and account identity are validated and suppressed behind unsafe per-operation opt-in."},
	"mavenlink-api-token":   {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace collaborator listing with current-user identity."},
	"meistertask-api-token": {Status: VerificationAuditReviewed, Batch: 9, Notes: "Current-person identity is schema-validated while undocumented authorization failures remain unknown."},
	"meraki-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace organization listing with administered identity."},
	"mindmeister-api-token": {Status: VerificationAuditReviewed, Batch: 9, Notes: "The v2 current-user identity replaces deprecated map listing and classifies structured scope errors."},
	"miro-api-token":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress OAuth token context before auth-only promotion."},
	"mixmax-api-key":        {Status: VerificationAuditBlocked, Batch: 9, Notes: "Current bounded identity endpoint contract is undocumented."},
	"moonclerk-api-key":     {Status: VerificationAuditBlocked, Batch: 9, Notes: "Legacy private forms API lacks a current provider contract."},
	"moralis-api-key":       {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe NFT lookup consumes Data API workload."},
	"newscatcher-api-key":   {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe subscription request consumes API-call allowance."},
	"ngc-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Split legacy, personal, and service key contracts."},
	"nimble-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correct current-user schema and token boundaries."},
	"nozbeteams-api-token":  {Status: VerificationAuditBlocked, Batch: 9, Notes: "Private user-list contract lacks current provider documentation."},
	"nvapi-key":             {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Establish the undocumented caller-info success schema before promotion."},
	"optimizely-api-key":    {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace project listing with current-user identity."},
	"overloop-api-key":      {Status: VerificationAuditBlocked, Batch: 9, Notes: "Authoritative bounded identity contract is unavailable."},

	"parseur-api-key":        {Status: VerificationAuditReviewed, Batch: 10, Notes: "Current and legacy key forms use the documented root discovery authentication response."},
	"paymo-api-key":          {Status: VerificationAuditReviewed, Batch: 10, Notes: "Current-user identity is schema-validated and suppressed."},
	"privacy-api-key":        {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe card listing retrieves sensitive financial metadata."},
	"prodpad-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Bound and validate private tag collection and structured errors."},
	"protocolsio-api-token":  {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Split client and OAuth contexts and suppress profile PII."},
	"qubole-api-token":       {Status: VerificationAuditBlocked, Batch: 10, Notes: "Account read can disclose cloud credentials and deployment context is unresolved."},
	"reachmail-api-key":      {Status: VerificationAuditReviewed, Batch: 10, Notes: "The documented current-user AccountId and request media types are validated with PII suppression."},
	"rev-ai-api-key":         {Status: VerificationAuditReviewed, Batch: 10, Notes: "Account email and numeric balances validated; account and financial metadata suppressed and ambiguous rejection stays unknown."},
	"ritekit-api-key":        {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe hashtag-statistics request consumes monthly allowance."},
	"simfin-api-key":         {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe financial-data collection consumes provider workload."},
	"squarespace-api-key":    {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate website identity and preserve subscription ambiguity."},
	"stitchdata-api-token":   {Status: VerificationAuditBlocked, Batch: 10, Notes: "Credential family, region, and source-management context are unresolved."},
	"supernotes-api-key":     {Status: VerificationAuditReviewed, Batch: 10, Notes: "Dedicated auth-check user identifier is schema-validated and suppressed."},
	"surveysparrow-api-key":  {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Migrate to regional v3 routing and bounded contact schema."},
	"survicate-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Retired v1 must migrate to bounded v2 survey metadata."},
	"teletype-api-key":       {Status: VerificationAuditBlocked, Batch: 10, Notes: "No authoritative endpoint, pagination, quota, or error contract is available."},
	"tly-api-key":            {Status: VerificationAuditReviewed, Batch: 10, Notes: "Paginated short-link listing is schema-validated and suppressed."},
	"travelpayouts-api-key":  {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe cached-flight lookup consumes request allowance."},
	"twist-api-token":        {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Correct token variants and suppress current-user and token data."},
	"upwave-api-key":         {Status: VerificationAuditBlocked, Batch: 10, Notes: "No authoritative current API, schema, quota, or error contract is available."},
	"vyte-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Bound event retrieval and validate sensitive event schema."},
	"webscraper-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Avoid query credential exposure and validate bounded sitemap response."},
	"worksnaps-api-key":      {Status: VerificationAuditBlocked, Batch: 10, Notes: "Legacy XML API lacks current authoritative authentication documentation."},
	"yousign-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate and suppress users response and resolve environment context."},
	"zenkit-api-key":         {Status: VerificationAuditReviewed, Batch: 10, Notes: "Current-user identity is schema-validated and suppressed."},
	"render-api-key":         {Status: VerificationAuditReviewed, Batch: 10, Notes: "Authenticated-user identity fields are schema-validated and profile data are suppressed."},
	"koyeb-api-token":        {Status: VerificationAuditReviewed, Batch: 10, Notes: "Nested current-user ID and email validated and suppressed; authorization and token-subtype ambiguity remain unknown."},
	"northflank-api-token":   {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Bound project listing and suppress project metadata."},
	"qovery-api-token":       {Status: VerificationAuditReviewed, Batch: 10, Notes: "Generated qov_ tokens use Token authentication and the documented account UUID contract with profile suppression."},
	"platformsh-api-token":   {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Confirm current Platform.sh and Upsun auth hosts."},
	"betterstack-api-key":    {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate JSON:API members and reconcile token format."},
	"helpscout-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate and suppress Docs collection envelope."},
	"mailerlite-api-key":     {Status: VerificationAuditReviewed, Batch: 10, Notes: "Static timezone probe replaced by one-group authenticated account collection; typed IDs/names validated and response suppressed."},
	"mandrill-api-key":       {Status: VerificationAuditReviewed, Batch: 10, Notes: "Transactional account identity and structured Invalid_Key errors are validated with quota and reputation suppression."},
	"capsulecrm-api-key":     {Status: VerificationAuditReviewed, Batch: 10, Notes: "Nested current-user ID and username validated and suppressed; forbidden responses no longer prove authentication."},
	"apollo-api-key":         {Status: VerificationAuditReviewed, Batch: 10, Notes: "Dedicated authentication health response is schema-validated and suppressed."},
	"lemlist-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate team identity and suppress webhook and member metadata."},
	"getresponse-api-key":    {Status: VerificationAuditBlocked, Batch: 10, Notes: "MAX host and tenant context cannot be derived from the key."},
	"alienvault-otx-api-key": {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Establish identity schema and current LevelBlue key boundaries."},
	"vpnapi-key":             {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe VPN lookup consumes daily request allowance."},
	"ipqualityscore-api-key": {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe fraud lookup consumes provider credits."},
	"ipstack-api-key":        {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe IP lookup consumes quota with automatic overages."},
	"ipgeolocation-api-key":  {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe geolocation consumes credits and may incur overages."},
	"zerotier-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Split Central and local-service token families."},
	"codacy-api-token":       {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Split account, repository, and self-hosted token contexts."},
	"weatherstack-api-key":   {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe current-weather lookup consumes metered quota."},
	"accuweather-api-key":    {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe city search consumes allowance and requires auth modernization."},
	"weatherbit-api-key":     {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe current-weather lookup consumes request quota."},
	"mapquest-api-key":       {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe geocoding lookup consumes transactions."},
	"aiven-token":            {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate project collection and reconcile token families."},
	"abuseipdb-api-key":      {Status: VerificationAuditReviewed, Batch: 10, Notes: "Known unsafe reputation check consumes daily allowance."},
	"sonarcloud-token":       {Status: VerificationAuditReviewed, Batch: 10, Notes: "Dedicated regional authentication validation is schema-classified and suppressed."},
	"jumpcloud-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Adopt current jca_ keys and suppress regional user data."},
	"pipedrive-api-token":    {Status: VerificationAuditReviewed, Batch: 10, Notes: "Current-user identity uses header auth and is schema-validated and suppressed."},
	"sparkpost-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 10, Notes: "Validate and suppress account identity and permission errors."},
	"dropbox-token":          {Status: VerificationAuditReviewed, Batch: 10, Notes: "Current-account identity and auth errors are schema-classified and suppressed."},
}

func buildVerificationAuditReport(ds []Detector) VerificationAuditReport {
	infos := RegistryInfo(ds)
	report := VerificationAuditReport{Total: len(infos), Entries: make([]VerificationAuditEntry, 0, len(infos))}
	for _, info := range infos {
		entry := VerificationAuditEntry{ID: info.ID, Name: info.Name, Verifiable: info.Verifiable, VerificationSafety: info.VerificationSafety}
		assessment, assessed := verificationAuditAssessments[info.ID]
		switch {
		case !info.Verifiable:
			entry.AuditStatus = VerificationAuditNoVerifier
			report.NoVerifier++
		case !assessed:
			if info.VerificationSafety == VerificationSafetyUnreviewed {
				entry.AuditStatus = VerificationAuditPending
				report.PendingReview++
			} else {
				entry.AuditStatus = VerificationAuditReviewed
				report.Reviewed++
			}
		default:
			entry.AuditStatus = assessment.Status
			entry.AuditBatch = assessment.Batch
			entry.Notes = assessment.Notes
			switch assessment.Status {
			case VerificationAuditReviewed:
				if info.VerificationSafety == VerificationSafetyUnreviewed {
					entry.AuditStatus = VerificationAuditPending
					report.PendingReview++
				} else {
					report.Reviewed++
				}
			case VerificationAuditRequiresHardening:
				report.RequiresHardening++
			case VerificationAuditBlocked:
				report.Blocked++
			default:
				report.PendingReview++
			}
		}
		report.Entries = append(report.Entries, entry)
	}
	return report
}
