package detectors

type VerificationAuditStatus string

const (
	VerificationAuditReviewed          VerificationAuditStatus = "reviewed"
	VerificationAuditRequiresHardening VerificationAuditStatus = "requires_hardening"
	VerificationAuditBlocked           VerificationAuditStatus = "blocked"
	VerificationAuditPending           VerificationAuditStatus = "pending_review"
	VerificationAuditNoVerifier        VerificationAuditStatus = "no_verifier"
)

type VerificationAuditEntry struct {
	ID                 string                  `json:"id"`
	Name               string                  `json:"name"`
	Verifiable         bool                    `json:"verifiable"`
	VerificationSafety VerificationSafety      `json:"verification_safety,omitempty"`
	AuditStatus        VerificationAuditStatus `json:"audit_status"`
	AuditBatch         int                     `json:"audit_batch,omitempty"`
	Notes              string                  `json:"notes,omitempty"`
}

type VerificationAuditReport struct {
	Total             int                      `json:"total"`
	Reviewed          int                      `json:"reviewed"`
	RequiresHardening int                      `json:"requires_hardening"`
	Blocked           int                      `json:"blocked"`
	PendingReview     int                      `json:"pending_review"`
	NoVerifier        int                      `json:"no_verifier"`
	Entries           []VerificationAuditEntry `json:"entries"`
}

type verificationAuditAssessment struct {
	Status VerificationAuditStatus
	Batch  int
	Notes  string
}

var verificationAuditAssessments = map[string]verificationAuditAssessment{
	"google-api-key":    {Status: VerificationAuditBlocked, Batch: 1, Notes: "Generic Google keys cannot be validated reliably against a single provider API."},
	"ngrok-token":       {Status: VerificationAuditBlocked, Batch: 1, Notes: "Detected credential families do not share a proven verification contract."},
	"langsmith-api-key": {Status: VerificationAuditBlocked, Batch: 1, Notes: "Cloud region, service-key tenant context, and self-hosted endpoint context are unresolved."},

	"openai-key":                {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Tighten supported key variants and require a list-shaped model response."},
	"pagerduty-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Split REST tokens from routing and integration keys before promotion."},
	"buildkite-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Route API, portal, and cluster-agent token variants independently."},
	"square-token":              {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Preserve local rejection of application secrets and validate merchant response structure."},
	"discord-webhook":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Webhook metadata identity is schema-validated and suppressed."},
	"grafana-token":             {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Grafana Cloud region context is incomplete."},
	"honeycomb-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Split key formats and correlate US or EU endpoint context."},
	"opsgenie-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Correlate global or EU endpoint context and harden restricted-key classification."},
	"webex-bot-token":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Bot identity fields are schema-validated and suppressed."},
	"huggingface-token":         {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Reconcile supported token formats and validate whoami response structure."},
	"groq-api-key":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "OpenAI-compatible model-list response is schema-validated."},
	"replicate-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Confirm current token length and validate account identity fields."},
	"airtable-pat":              {Status: VerificationAuditReviewed, Batch: 1, Notes: "Whoami identity is schema-validated and suppressed."},
	"asana-pat":                 {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-user data.gid is schema-validated and suppressed."},
	"clickup-token":             {Status: VerificationAuditReviewed, Batch: 1, Notes: "Current-user identity is schema-validated and suppressed."},
	"typeform-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Preserve structured authentication errors and validate user identity."},
	"hubspot-private-app-token": {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate usage response and distinguish structured scope failures."},
	"mailchimp-key":             {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate data-center suffix and ping response."},
	"klaviyo-key":               {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Replace profile lookup with bounded account metadata."},
	"iterable-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Resolve key type and region ambiguity before classifying rejection."},
	"nightfall-api-key":         {Status: VerificationAuditReviewed, Batch: 1, Notes: "Read-only detection-rules collection is validated and suppressed."},
	"pinecone-api-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "Control-plane index collection is schema-validated and suppressed."},
	"elevenlabs-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "User identity response is schema-validated and suppressed."},
	"xai-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Switch to the documented API-key identity endpoint."},
	"cohere-api-key":            {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated; context-sensitive rejection remains unknown."},
	"mistral-api-key":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated; hosted-key rejection remains unknown."},
	"togetherai-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Top-level model-list response is schema-validated and suppressed."},
	"fireworksai-api-key":       {Status: VerificationAuditReviewed, Batch: 1, Notes: "Bounded model response is schema-validated and suppressed."},
	"voyageai-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate bounded file-list response and suppress metadata."},
	"perplexity-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Router model-list response is schema-validated and suppressed."},
	"openrouter-api-key":        {Status: VerificationAuditReviewed, Batch: 1, Notes: "Uses the documented key endpoint with nested data validation."},
	"ai21-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate file-list response and distinguish malformed requests."},
	"cerebras-api-key":          {Status: VerificationAuditReviewed, Batch: 1, Notes: "Model-list response is schema-validated and forbidden responses remain ambiguous."},
	"baseten-api-key":           {Status: VerificationAuditReviewed, Batch: 1, Notes: "Uses bearer management authentication with model-list validation."},
	"runpod-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Move to the documented REST v1 pods endpoint."},
	"fal-ai-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Prove authenticated model-list semantics and validate key boundaries."},
	"novita-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Replace the public model list with the authenticated balance endpoint."},
	"zilliz-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Preserve application-code classification and suppress project data."},
	"chroma-cloud-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate cloud identity fields and region fallback."},
	"harness-pat":               {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate SaaS current-user response while preserving self-managed ambiguity."},
	"zoho-crm-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate user response and bounded regional fallback."},
	"intercom-access-token":     {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate me response and supported token encoding."},
	"front-api-token":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Narrow token variants and validate me response."},
	"segment-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate workspace collection response and suppress metadata."},
	"posthog-personal-api-key":  {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate user identity and preserve self-hosted endpoint ambiguity."},
	"launchdarkly-key":          {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Validate caller identity and preserve local rejection of SDK keys."},
	"postmark-token":            {Status: VerificationAuditRequiresHardening, Batch: 1, Notes: "Route server and account token variants independently."},

	"coda-api-token":                     {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate whoami identity and suppress response metadata."},
	"calendly-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate resource identity and realistic JWT boundaries."},
	"monday-api-token":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress GraphQL identity response and harden error classification."},
	"flyio-token":                        {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate authentication response before auth-only promotion."},
	"cloudflare-ca-key":                  {Status: VerificationAuditBlocked, Batch: 2, Notes: "Cloudflare Origin CA service keys retire on 2026-09-30."},
	"azure-app-config-connection-string": {Status: VerificationAuditReviewed, Batch: 2, Notes: "Signed read-only App Configuration request is context-complete and suppressed."},
	"azure-storage-connection-string":    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Signed bounded Azure Storage list request is context-complete and suppressed."},
	"spectralops-token":                  {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only user collection contract is bounded and suppressed."},
	"atlassian-api-token":                {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate organization collection and suppress metadata."},
	"salesforce-access-token":            {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate userinfo and preserve production or sandbox endpoint ambiguity."},
	"openphone-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded users response and provider rename contract."},
	"dialpad-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate company identity and preserve restricted-key ambiguity."},
	"ringover-api-key":                   {Status: VerificationAuditReviewed, Batch: 2, Notes: "Read-only user collection is schema-classified and suppressed."},
	"callrail-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded accounts response and suppress metadata."},
	"mailjet-basic-auth":                 {Status: VerificationAuditReviewed, Batch: 2, Notes: "Credential parsing and bounded message request are validated and suppressed."},
	"urlscan-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate quota response and suppress account details."},
	"deepseek-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate model-list response and suppress provider errors."},
	"weightsandbiases-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress GraphQL identity and preserve self-hosted ambiguity."},
	"assemblyai-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded transcript collection and regional fallback."},
	"deepgram-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate projects response and suppress metadata."},
	"contentful-pat":                     {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded spaces response and regional fallback."},
	"storyblok-personal-access-token":    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded spaces response across management regions."},
	"storyblok-access-token":             {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate current-space response across CDN regions."},
	"sanity-auth-token":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Resolve personal and robot token endpoint compatibility."},
	"datocms-api-token":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate JSON API site identity and suppress metadata."},
	"elastic-email-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Replace sensitive key listing with bounded account identity."},
	"webflow-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Move to documented token introspection and validate identity."},
	"mapbox-secret-token":                {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate token inspection response and suppress authorization metadata."},
	"locationiq-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate balance response and regional fallback."},
	"coinapi-key":                        {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate limits response and suppress quota metadata."},
	"onfido-api-token":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded applicant collection and suppress PII."},
	"unit-api-token":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Bounded account collection is schema-classified and suppressed."},
	"increase-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API credentials from webhook and OAuth secrets."},
	"lithic-api-key":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Bounded account-holder collection is schema-classified and suppressed."},
	"persona-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API tokens from webhook secrets and suppress inquiry PII."},
	"apisports-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress subscription response and narrow invalid markers."},
	"opticodds-api-key":                  {Status: VerificationAuditReviewed, Batch: 2, Notes: "Static sports collection is schema-classified and suppressed."},
	"complyadvantage-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Replace unbounded regional user lists with a bounded contract."},
	"bitgo-access-token":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Confirm test host and validate user identity."},
	"circle-api-key":                     {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Split API keys from webhook secrets and support sandbox context."},
	"trulioo-api-key":                    {Status: VerificationAuditReviewed, Batch: 2, Notes: "Dedicated authentication endpoint is schema-classified and suppressed."},
	"etherscan-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress quota-bearing chain response and test provider error codes."},
	"guardian-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate bounded search response and suppress article metadata."},
	"sourcegraph-token":                  {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress cloud identity and preserve local token no-request behavior."},
	"sourcegraph-cody-token":             {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate limits response and preserve forbidden ambiguity."},
	"snyk-api-key":                       {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate regional self response and cap fallback requests."},
	"uptimerobot-api-key":                {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Suppress bounded monitor response and test application errors."},
	"statuspage-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Bound or replace page collection and confirm authorization form."},
	"sendinblue-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 2, Notes: "Validate account identity and suppress plan and address data."},
	"teamwork-token":                     {Status: VerificationAuditReviewed, Batch: 2, Notes: "Launchpad identity response is schema-classified and suppressed."},

	"salesblink-api-key":                  {Status: VerificationAuditBlocked, Batch: 3, Notes: "No authoritative provider verification contract or error schema is available."},
	"mailmodo-api-key":                    {Status: VerificationAuditBlocked, Batch: 3, Notes: "No documented bounded verification endpoint or response contract is available."},
	"triggerdev-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Narrow supported key variants and validate the top-level run-list schema."},
	"resend-api-key":                      {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Narrow key format and schema-classify list and structured error responses."},
	"clerk-secret-key":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Replace the deprecated clients probe with a current bounded endpoint."},
	"workos-api-key":                      {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate the organization-list schema and suppress organization metadata."},
	"liveblocks-secret-key":               {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate room-list and structured error schemas and suppress room metadata."},
	"polar-access-token":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve production and sandbox routing and validate organization responses."},
	"temporal-cloud-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split API keys from client secrets and validate current identity."},
	"trayio-api-token":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve token families and regional hosts before promotion."},
	"airbyte-api-token":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "Cloud, self-managed, and client-secret credential contexts are conflated."},
	"hightouch-api-key":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "The current workspace endpoint lacks a public provider-owned contract."},
	"deno-deploy-token":                   {Status: VerificationAuditBlocked, Batch: 3, Notes: "The implemented organization collection route is absent from the current API contract."},
	"supabase-management-token":           {Status: VerificationAuditReviewed, Batch: 3, Notes: "Cloud project collection is schema-validated and suppressed."},
	"prefect-api-key":                     {Status: VerificationAuditReviewed, Batch: 3, Notes: "Cloud workspace collection is schema-validated and suppressed."},
	"figma-pat":                           {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split personal tokens from OAuth variants and validate current-user identity."},
	"saladcloud-api-key":                  {Status: VerificationAuditBlocked, Batch: 3, Notes: "Safe reads require organization context that the detector does not capture."},
	"neon-api-key":                        {Status: VerificationAuditReviewed, Batch: 3, Notes: "Dedicated authentication response is schema-validated and suppressed."},
	"turso-api-token":                     {Status: VerificationAuditReviewed, Batch: 3, Notes: "Organization collection is schema-validated and suppressed."},
	"xata-api-key":                        {Status: VerificationAuditReviewed, Batch: 3, Notes: "Organization collection is schema-validated and suppressed."},
	"cockroachcloud-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Narrow credential context and validate the cluster-list schema."},
	"motherduck-token":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Require top-level account schema and structured authorization errors."},
	"singlestore-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate current-organization identity and preserve allowlist ambiguity."},
	"gcp-service-account-json":            {Status: VerificationAuditReviewed, Batch: 3, Notes: "Signed read-only token exchange is schema-classified and suppressed."},
	"gcp-application-default-credentials": {Status: VerificationAuditReviewed, Batch: 3, Notes: "Authorized-user token exchange is schema-classified and suppressed."},
	"closecrm-api-key":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate current-user identity and remove broad restricted-account classification."},
	"paystack-secret-key":                 {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate balance schema and suppress financial response data."},
	"wrike-access-token":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Harden token format, regional fallback, and current-contact schema."},
	"flutterwave-secret-key":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Support current key variants and suppress validated balance data."},
	"pagarme-live-key":                    {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split current and legacy key formats before endpoint verification."},
	"rechargepayments-token":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate store identity and distinguish scoped authorization failures."},
	"lemonsqueezy-api-token":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Harden JWT format and validate JSON:API user identity."},
	"cloudinary-url":                      {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Correlate cloud identity and suppress validated configuration data."},
	"helpcrunch-api-key":                  {Status: VerificationAuditReviewed, Batch: 3, Notes: "Department collection and structured rejection are schema-classified and suppressed."},
	"line-messaging-token":                {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Resolve channel-token variants and validate bot identity."},
	"courier-api-key":                     {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Move to the current preference-sections endpoint and schema."},
	"virustotal-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Parse structured errors, validate sentinel identity, and suppress metadata."},
	"shodan-api-key":                      {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate top-level API-info fields and suppress quota metadata."},
	"securitytrails-api-key":              {Status: VerificationAuditReviewed, Batch: 3, Notes: "Dedicated ping response is schema-classified and suppressed."},
	"newsapi-key":                         {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate article-list schema and structured key status errors."},
	"openweather-api-key":                 {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Schema-classify weather responses and account for quota-bearing workload."},
	"tomorrowio-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Harden key format, response schema, and quota-bearing workload handling."},
	"here-api-key":                        {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate geocode results and preserve feature-restriction ambiguity."},
	"polygon-api-key":                     {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Update provider routing and avoid quota-bearing ticker lookup."},
	"scaleway-secret-key":                 {Status: VerificationAuditBlocked, Batch: 3, Notes: "Project verification requires organization and access-key context."},
	"braintree-access-token":              {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Suppress GraphQL responses and harden authentication error classification."},
	"webex-access-token":                  {Status: VerificationAuditReviewed, Batch: 3, Notes: "Current-user identity is schema-validated and suppressed."},
	"detectify-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Split V2 and V3 credential formats and endpoint contracts."},
	"twitter-bearer-token":                {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Replace the billable post lookup with a bounded account endpoint."},
	"twitch-access-token":                 {Status: VerificationAuditRequiresHardening, Batch: 3, Notes: "Validate token-introspection schema and suppress identity and scope data."},

	"ipinfo-token":                    {Status: VerificationAuditReviewed, Batch: 4, Notes: "Unlimited Lite identity lookup is schema-validated and suppressed."},
	"coinlayer-api-key":               {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota and may incur overage charges."},
	"cryptocompare-api-key":           {Status: VerificationAuditBlocked, Batch: 4, Notes: "The legacy endpoint and key contract are absent from current provider documentation."},
	"worldcoinindex-api-key":          {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes a scarce hourly request quota."},
	"fixerio-api-key":                 {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"currencylayer-api-key":           {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"exchangerate-api-key":            {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe quota verification itself consumes provider request quota."},
	"exchangeratesapi-api-key":        {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes metered quota with automatic overages."},
	"currencyfreaks-api-key":          {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes a hard monthly request quota."},
	"currencyscoop-api-key":           {Status: VerificationAuditBlocked, Batch: 4, Notes: "Legacy CurrencyScoop keys are not proven compatible with CurrencyBeacon."},
	"fastforex-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Move to a bounded usage contract and correct documented key boundaries."},
	"marketstack-api-key":             {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification consumes quota with automatic paid overages."},
	"financialmodelingprep-api-key":   {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe exchange lookup consumes provider request quota."},
	"finnhub-api-key":                 {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe quote lookup consumes provider request quota."},
	"tradier-token":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Correct token boundaries, support sandbox context, and suppress profile data."},
	"twelvedata-api-key":              {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Suppress account usage data and document one-credit verification workload."},
	"vatlayer-api-key":                {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification may incur automatic per-request overages."},
	"worldweather-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Resolve key boundaries and validate and suppress weather responses."},
	"positionstack-api-key":           {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe geocoding verification may incur automatic overages."},
	"geocodio-api-key":                {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe verification performs a billable geocoding lookup."},
	"telnyx-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate balance schema and suppress financial metadata."},
	"vagrant-cloud-token":             {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Suppress authentication response and account for scheduled service shutdown."},
	"zeplin-token":                    {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Separate personal tokens from OAuth variants and suppress current-user data."},
	"vultr-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate account schema and preserve ACL or IP restriction ambiguity."},
	"airbrake-user-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate bounded project collection and suppress project metadata."},
	"infura-project-id":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Use the lowest-cost RPC probe and preserve endpoint-security ambiguity."},
	"messagebird-api-key":             {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Correct live and test key variants and suppress validated balance data."},
	"pinata-jwt":                      {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated authentication response is schema-validated and suppressed."},
	"pushbullet-token":                {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Confirm token boundaries and validate and suppress current-user identity."},
	"stormglass-api-key":              {Status: VerificationAuditReviewed, Batch: 4, Notes: "Known unsafe weather verification consumes scarce metered requests."},
	"bunny-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace undocumented endpoint and split account, Stream, and storage credentials."},
	"imgix-api-token":                 {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split API and secure URL tokens and suppress source metadata."},
	"keycdn-api-key":                  {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace the unbounded sensitive zone listing with a bounded contract."},
	"eventbrite-private-token":        {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate and suppress current-user identity."},
	"harvest-access-token":            {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate and suppress Harvest user and account metadata."},
	"lokalise-token":                  {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate bounded project collection and structured errors."},
	"nylas-api-key":                   {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split API keys from client secrets and correlate regional context."},
	"pipedream-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Narrow credential types and validate and suppress current-user identity."},
	"percy-token":                     {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Distinguish public fallback and token permissions before promotion."},
	"crowdin-token":                   {Status: VerificationAuditBlocked, Batch: 4, Notes: "Crowdin.com and organization-specific Enterprise hosts are unresolved."},
	"sendbird-organization-api-token": {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Replace application listing because it returns additional API tokens."},
	"checkly-api-key":                 {Status: VerificationAuditBlocked, Batch: 4, Notes: "Verification requires account context not captured by the detector."},
	"incidentio-api-key":              {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated identity response is schema-validated and suppressed."},
	"firehydrant-api-key":             {Status: VerificationAuditReviewed, Batch: 4, Notes: "Dedicated ping response is schema-validated and suppressed."},
	"ilert-api-key":                   {Status: VerificationAuditReviewed, Batch: 4, Notes: "Current-user identity is schema-validated and suppressed."},
	"semgrep-app-token":               {Status: VerificationAuditReviewed, Batch: 4, Notes: "Deployment collection is schema-validated and suppressed."},
	"socketdev-api-key":               {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Validate organizations, suppress metadata, and account for request quota."},
	"cronitor-api-key":                {Status: VerificationAuditRequiresHardening, Batch: 4, Notes: "Split telemetry-only and resource-scoped keys before bounded reads."},
	"gocardless-access-token":         {Status: VerificationAuditReviewed, Batch: 4, Notes: "Environment-specific creditor collection is schema-validated and suppressed."},
	"gumroad-access-token":            {Status: VerificationAuditReviewed, Batch: 4, Notes: "Seller identity response is schema-validated and suppressed."},

	"hellosign-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dropbox Sign account identity is schema-validated and suppressed."},
	"mailboxlayer-api-key":   {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe email validation consumes metered quota with automatic overages."},
	"mediastack-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe news lookup consumes metered quota with automatic overages."},
	"opencage-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding consumes request allowance and may incur charges."},
	"packagecloud-token":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded repository collection is schema-validated and suppressed."},
	"phrase-access-token":    {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Split legacy and Platform token families and validate regional current-user identity."},
	"semaphore-api-token":    {Status: VerificationAuditBlocked, Batch: 5, Notes: "Current API requires organization context absent from the detector."},
	"scrutinizer-token":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Bound repository pagination and validate the embedded collection envelope."},
	"openuv-api-key":         {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe live UV calculation consumes provider workload."},
	"pandascore-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe static-data lookup consumes hourly request allowance."},
	"paperform-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded forms collection is schema-validated and suppressed."},
	"parsehub-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate bounded project collection and suppress project metadata."},
	"pdfshift-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Adopt current X-API-Key credentials and validate credits usage."},
	"peopledatalabs-api-key": {Status: VerificationAuditReviewed, Batch: 5, Notes: "Parameterless authentication probe uses structured errors and cannot produce a billable match."},
	"scrapingbee-api-key":    {Status: VerificationAuditBlocked, Batch: 5, Notes: "The usage route lacks a current public provider contract."},
	"serpstack-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe live SERP lookup consumes metered quota with automatic overages."},
	"shotstack-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate nested template-list responses across stage and production."},
	"abstract-api-key":       {Status: VerificationAuditBlocked, Batch: 5, Notes: "Product-specific Abstract keys cannot be validated against one generic endpoint."},
	"alchemy-api-key":        {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe RPC verification consumes billed compute units."},
	"apilayer-key":           {Status: VerificationAuditBlocked, Batch: 5, Notes: "Generic marketplace keys lack subscribed-product context."},
	"bannerbear-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Separate V2 keys and validate and suppress account metadata."},
	"baremetrics-api-key":    {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate and suppress the account response."},
	"beamer-api-key":         {Status: VerificationAuditReviewed, Batch: 5, Notes: "Read-only configured URL response is schema-validated and suppressed."},
	"bitbar-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Establish current identity schema and suppress user metadata."},
	"blazemeter-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Narrow API Monitoring tokens and validate account identity."},
	"buttercms-api-token":    {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe content lookup consumes metered usage with paid overages."},
	"canny-api-key":          {Status: VerificationAuditBlocked, Batch: 5, Notes: "Board listing is unbounded and retrieves private-board token material."},
	"chartmogul-api-key":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dedicated ping response is schema-validated and suppressed."},
	"clearbit-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe enrichment lookup consumes quota and processes personal data."},
	"clockify-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate and suppress current-user identity and workspace metadata."},
	"cloudconvert-api-key":   {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate current-user identity and resolve sandbox context."},
	"convertapi-secret":      {Status: VerificationAuditBlocked, Batch: 5, Notes: "Detected secret format is not mapped to the Master Token accepted by the endpoint."},
	"convertkit-api-secret":  {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate the deprecated V3 account schema and suppress account metadata."},
	"dailyco-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Replace room listing with domain identity validation."},
	"fullstory-api-key":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Dedicated authentication role response is schema-validated and suppressed."},
	"flagsmith-server-key":   {Status: VerificationAuditBlocked, Batch: 5, Notes: "Client and server keys plus self-hosted API bases are conflated."},
	"growthbook-api-key":     {Status: VerificationAuditBlocked, Batch: 5, Notes: "Cloud and self-hosted secret keys require endpoint context."},
	"configcat-sdk-key":      {Status: VerificationAuditBlocked, Batch: 5, Notes: "Config download is metered and deployment or CDN context is unresolved."},
	"pendo-integration-key":  {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Correlate regional host and validate and suppress metadata schema."},
	"kustomer-api-token":     {Status: VerificationAuditReviewed, Batch: 5, Notes: "Current-user identity is schema-validated and suppressed."},
	"productboard-api-token": {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Bound member listing and validate and suppress member data."},
	"planhat-api-token":      {Status: VerificationAuditReviewed, Batch: 5, Notes: "Bounded user collection is schema-validated and suppressed."},
	"geoapify-api-key":       {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding lookup consumes provider credits."},
	"graphhopper-api-key":    {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe geocoding lookup consumes provider credits."},
	"hunter-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate and suppress free account and quota metadata."},
	"imagekit-private-key":   {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate file collection and suppress file metadata."},
	"kickbox-api-key":        {Status: VerificationAuditReviewed, Batch: 5, Notes: "Known unsafe email validation consumes credits and may trigger auto-recharge."},
	"klipfolio-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Require successful top-level metadata and test structured errors."},
	"lob-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Validate bounded address collection and suppress PII."},
	"moosend-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 5, Notes: "Establish current response and error fixtures before promotion."},

	"numverify-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe phone validation consumes metered quota and may incur overages."},
	"omnisend-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Current-brand identity is schema-validated and suppressed."},
	"pandadoc-api-key":            {Status: VerificationAuditBlocked, Batch: 6, Notes: "No current bounded identity endpoint is documented."},
	"partnerstack-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Split Partner and Vendor credentials and bound partnership reads."},
	"paymongo-secret-key":         {Status: VerificationAuditBlocked, Batch: 6, Notes: "Webhook listing retrieves additional signing secrets."},
	"photoroom-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Non-processing account usage response is schema-validated and suppressed."},
	"qase-api-token":              {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate project schema and preserve Enterprise host ambiguity."},
	"replyio-api-key":             {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Move to current whoami endpoint and Bearer authentication."},
	"restpack-htmltopdf-api-key":  {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress the non-rendering usage response."},
	"restpack-screenshot-api-key": {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Require the complete usage schema and preserve subscription ambiguity."},
	"rocketreach-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress bounded account and credit metadata."},
	"route4me-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Replace or strictly bound address-book verification."},
	"salesflare-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Replace contact listing with current-user identity."},
	"attio-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Token introspection is schema-classified and suppressed."},
	"affinity-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Whoami identity and grant are schema-validated and suppressed."},
	"salesloft-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Narrow API-key format and validate current-user identity."},
	"instantly-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Bounded current-workspace response is schema-classified and suppressed."},
	"smartlead-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Replace unbounded campaign listing with a bounded contract."},
	"greenhouse-harvest-api-key":  {Status: VerificationAuditBlocked, Batch: 6, Notes: "Legacy Harvest verification is retired and v3 requires OAuth context."},
	"ashby-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Dedicated API-key identity response is schema-validated and suppressed."},
	"workable-api-token":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress account collection metadata."},
	"smartrecruiters-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Separate SmartToken and OAuth contracts before identity verification."},
	"deel-api-token":              {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe contract read retrieves sensitive HR records across unresolved environments."},
	"gusto-api-token":             {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Separate environments and credential types before token introspection."},
	"airvisual-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe environmental lookup consumes metered workload."},
	"ambee-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe air-quality lookup consumes metered workload."},
	"apiflash-access-key":         {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress quota endpoint data."},
	"apitemplate-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Read-only template collection is schema-classified and suppressed."},
	"appfollow-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe account-user read consumes provider API credits."},
	"autoklose-api-key":           {Status: VerificationAuditBlocked, Batch: 6, Notes: "The implemented endpoint redirects and no current API contract is documented."},
	"aviationstack-api-key":       {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe flight lookup consumes metered quota with automatic overages."},
	"ayrshare-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress linked-account user profile metadata."},
	"besttime-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Dedicated private-key validation is schema-classified and suppressed."},
	"brandfetch-api-key":          {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe brand lookup consumes quota with automatic overages."},
	"browshot-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate and suppress account balance metadata."},
	"calendarific-api-key":        {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe countries lookup consumes monthly request allowance."},
	"craftmypdf-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Correct account schema and padded key format before promotion."},
	"currentsapi-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe latest-news lookup consumes daily request quota."},
	"debounce-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe mailbox validation consumes a paid verification credit."},
	"detectlanguage-api-key":      {Status: VerificationAuditReviewed, Batch: 6, Notes: "Account-status authentication response is schema-validated and suppressed."},
	"codemagic-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Bound and validate app collection and suppress workflow metadata."},
	"diffbot-api-token":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Read-only account usage response is schema-classified and suppressed."},
	"ethplorer-api-key":           {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe blockchain lookup consumes provider request allowance."},
	"geckoboard-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Require exact authentication-ping schema and reconcile key format."},
	"holidayapi-key":              {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe countries lookup consumes monthly request allowance."},
	"ip2location-api-key":         {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe geolocation lookup consumes quota with automatic overages."},
	"ipapi-api-key":               {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe IP lookup consumes quota with paid overages."},
	"ipinfodb-api-key":            {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe IP-country lookup consumes provider workload."},
	"jotform-api-key":             {Status: VerificationAuditRequiresHardening, Batch: 6, Notes: "Validate identity, suppress user data, and handle unsupported custom hosts."},
	"languagelayer-api-key":       {Status: VerificationAuditReviewed, Batch: 6, Notes: "Known unsafe language-data lookup consumes quota with automatic overages."},

	"linkpreview-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe verification performs a metered remote-page crawl."},
	"mockaroo-api-key":         {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe metadata read consumes scarce request allowance."},
	"oanda-api-token":          {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress private account lists across environments."},
	"onfleet-api-key":          {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Establish and suppress the dedicated authentication success contract."},
	"pepipost-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Move legacy verification to documented regional Netcore V6."},
	"pivotaltracker-api-token": {Status: VerificationAuditBlocked, Batch: 7, Notes: "The current service and provider-owned API contract are unavailable."},
	"pixabay-api-key":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe media search consumes provider request allowance."},
	"podio-api-token":          {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress user status and handle HTTP 420 rate limits."},
	"rawg-api-key":             {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe game-database lookup consumes metered requests."},
	"selectpdf-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Non-rendering subscription usage response is schema-validated and suppressed."},
	"shipday-api-key":          {Status: VerificationAuditReviewed, Batch: 7, Notes: "Read-only carrier collection is schema-classified and suppressed."},
	"signable-api-key":         {Status: VerificationAuditBlocked, Batch: 7, Notes: "Authoritative workload, quota, and billing documentation is unavailable."},
	"signaturit-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Harden production and sandbox fallback before promotion."},
	"simplesat-api-key":        {Status: VerificationAuditBlocked, Batch: 7, Notes: "Authoritative endpoint, quota, and billing contract is unavailable."},
	"snipcart-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate documented paginated order envelope and suppress PII."},
	"spoonacular-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe recipe search consumes billable quota points."},
	"sportsmonk-api-token":     {Status: VerificationAuditReviewed, Batch: 7, Notes: "Bounded league response is schema-classified and suppressed."},
	"statuscake-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress bounded private monitor responses."},
	"stockdata-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe quote lookup consumes daily request allowance."},
	"shippo-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress address collection and structured errors."},
	"easypost-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress static carrier metadata."},
	"shipengine-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress regional account settings."},
	"aftership-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Add required content type and validate courier response."},
	"easyship-api-token":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate account identity and suppress billing metadata."},
	"tatum-api-key":            {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe version probe consumes one provider credit."},
	"taxjar-api-token":         {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Correct token boundaries and validate static categories."},
	"tiingo-api-token":         {Status: VerificationAuditReviewed, Batch: 7, Notes: "Dedicated authentication response is schema-classified and suppressed."},
	"timecamp-api-token":       {Status: VerificationAuditReviewed, Batch: 7, Notes: "Current-user response is schema-classified and suppressed."},
	"toggltrack-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress current-user response containing token data."},
	"tomtom-api-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe raster-tile lookup consumes geospatial allowance."},
	"transferwise-api-token":   {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress user PII across production and sandbox."},
	"unsplash-access-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe photo lookup consumes application request allowance."},
	"userstack-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe user-agent lookup consumes quota with paid overages."},
	"visualcrossing-api-key":   {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe weather lookup consumes record-metered workload."},
	"voicegain-api-key":        {Status: VerificationAuditBlocked, Batch: 7, Notes: "Cloud and Edge JWTs require deployment-specific endpoint context."},
	"yelp-api-key":             {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe business search is priced per API call."},
	"ynab-api-token":           {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Replace plan listing with user identity validation."},
	"zerobounce-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Use POST balance probe, suppress credits, and resolve regional routing."},
	"smartsheet-access-token":  {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Validate and suppress current-user identity across regions."},
	"thousandeyes-token":       {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Split OAuth and legacy credentials and preserve account-lockout ambiguity."},
	"ticketmaster-api-key":     {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe event search consumes daily API quota."},
	"theoddsapi-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Documented zero-quota sports catalog is array-validated and suppressed."},
	"teachable-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Bound and validate documented courses and metadata response."},
	"ubidots-token":            {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Confirm current identity endpoint and suppress user metadata."},
	"uclassify-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe classifier metadata consumes daily call allowance."},
	"upcdatabase-api-key":      {Status: VerificationAuditReviewed, Batch: 7, Notes: "Account endpoint avoids barcode quota and suppresses metadata."},
	"uplead-api-key":           {Status: VerificationAuditReviewed, Batch: 7, Notes: "Credits endpoint avoids enrichment billing and suppresses metadata."},
	"vbout-api-key":            {Status: VerificationAuditRequiresHardening, Batch: 7, Notes: "Update verifier to current top-level business schema."},
	"veriphone-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Non-validation credits response is schema-classified and suppressed."},
	"walkscore-api-key":        {Status: VerificationAuditReviewed, Batch: 7, Notes: "Known unsafe walkability lookup consumes daily quota."},

	"whoxy-api-key":         {Status: VerificationAuditReviewed, Batch: 8, Notes: "Non-lookup account balance response is schema-classified and suppressed."},
	"wistia-api-token":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Move to modern token identity endpoint and suppress output."},
	"wit-ai-token":          {Status: VerificationAuditBlocked, Batch: 8, Notes: "No current provider-owned verification contract is available."},
	"ticket-tailor-api-key": {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Replace order retrieval with lower-sensitivity box-office metadata."},
	"tmetric-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate and suppress current-user and workspace metadata."},
	"signupgenius-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe profile verification consumes limited daily API allowance."},
	"skrapp-api-key":        {Status: VerificationAuditReviewed, Batch: 8, Notes: "Free account-credit response is schema-classified and suppressed."},
	"sslmate-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Separate product credential families and parse structured errors."},
	"storecove-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate experimental country-specification response."},
	"stormboard-api-key":    {Status: VerificationAuditBlocked, Batch: 8, Notes: "Implemented profile route lacks a current provider contract."},
	"streak-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Use canonical host and validate and suppress current-user identity."},
	"abyssale-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Dedicated no-body authentication probe is schema-classified and suppressed."},
	"adafruit-io-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Confirm current-user contract and split modern and legacy key variants."},
	"alconost-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Confirm canonical Nitro host and current account schema."},
	"aletheia-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe financial-data lookup consumes monthly allowance."},
	"allsports-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe countries lookup consumes scarce hourly allowance."},
	"apacta-api-key":        {Status: VerificationAuditBlocked, Batch: 8, Notes: "Current endpoint, auth, pagination, and error contract are unavailable."},
	"api2cart-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe cart listing consumes paid request allowance."},
	"apimatic-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Bound generation listing and validate current response schema."},
	"apimetrics-api-key":    {Status: VerificationAuditReviewed, Batch: 8, Notes: "Bounded API-call collection is schema-classified and suppressed."},
	"appointedd-api-key":    {Status: VerificationAuditBlocked, Batch: 8, Notes: "Implemented availability route is absent from the current API contract."},
	"atera-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate and suppress bounded agent response."},
	"autopilot-api-key":     {Status: VerificationAuditBlocked, Batch: 8, Notes: "Only a legacy contract is available; current semantics are unresolved."},
	"axonaut-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Apply documented pagination and validate private company collection."},
	"beebole-api-token":     {Status: VerificationAuditBlocked, Batch: 8, Notes: "No authoritative current custom_field.list contract is available."},
	"bombbomb-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate current-user identity and structured errors."},
	"borgbase-api-key":      {Status: VerificationAuditReviewed, Batch: 8, Notes: "Read-only GraphQL repository-ID query is schema-classified and suppressed."},
	"buddyns-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Documented user identity endpoint is schema-classified and suppressed."},
	"bugherd-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe project listing retrieves additional project API keys."},
	"caflou-api-key":        {Status: VerificationAuditBlocked, Batch: 8, Notes: "No authoritative account-list pagination or schema contract is available."},
	"calorieninja-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe nutrition enrichment consumes product workload."},
	"captaindata-api-key":   {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate documented account and credit fields before promotion."},
	"chatbot-api-key":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Read-only story collection is schema-classified and suppressed."},
	"cliengo-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Migrate legacy UUID query credentials to current Bearer tokens."},
	"avaza-api-token":       {Status: VerificationAuditReviewed, Batch: 8, Notes: "Account response is schema-classified and suppressed."},
	"cloudplan-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Establish current account schema and suppress response."},
	"cloverly-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Establish a current account endpoint and error contract."},
	"clustdoc-api-key":      {Status: VerificationAuditBlocked, Batch: 8, Notes: "Current route resolves to an HTML login flow."},
	"codequiry-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Move check listing to dedicated auth validation endpoint."},
	"column-api-key":        {Status: VerificationAuditReviewed, Batch: 8, Notes: "Bounded entity collection is schema-classified and suppressed."},
	"commodities-api-key":   {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe public-symbol lookup consumes metered request quota."},
	"countrylayer-api-key":  {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe country-data lookup consumes metered request quota."},
	"dandelion-api-key":     {Status: VerificationAuditReviewed, Batch: 8, Notes: "Known unsafe NLP language detection consumes processing units."},
	"datagov-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Replace retired endpoint with a live bounded participating-agency contract."},
	"diggernaut-api-key":    {Status: VerificationAuditReviewed, Batch: 8, Notes: "Documented project collection is schema-classified and suppressed."},
	"docparser-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Replace parser listing with documented Basic-auth ping."},
	"dynalist-api-token":    {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Suppress private file-list metadata and harden application errors."},
	"dyspatch-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Update API version and validate typed template collection."},
	"envoy-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Validate locations schema and confirm key format and media version."},
	"everhour-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 8, Notes: "Establish current identity contract and suppress user data."},

	"feedier-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Move to a current documented bounded v3 resource."},
	"finage-api-key":        {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe financial-data lookup consumes product workload."},
	"flatio-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress current-user identity and structured errors."},
	"flexport-api-key":      {Status: VerificationAuditBlocked, Batch: 9, Notes: "Detected key format is not tied to a current documented endpoint."},
	"flickr-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Suppress echoed key material and tighten application-key boundaries."},
	"flightapi-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe travel-data lookup consumes API credits."},
	"float-api-key":         {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace private people listing with a lower-sensitivity account read."},
	"frameio-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Split legacy and Adobe IMS token contracts and suppress identity."},
	"fulcrum-api-token":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correlate regional host and validate private user collection."},
	"geocodify-api-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe forward geocoding consumes monthly quota."},
	"getgeoapi-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe currency-list lookup consumes daily allowance."},
	"glassnode-api-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "Credit-free metadata collection is array-validated and suppressed."},
	"goodday-api-key":       {Status: VerificationAuditBlocked, Batch: 9, Notes: "Authoritative pagination, quota, and error contracts are unavailable."},
	"groovehq-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy current-user identity is schema-validated and suppressed."},
	"gtmetrix-api-key":      {Status: VerificationAuditReviewed, Batch: 9, Notes: "Non-testing account-status response is schema-classified and suppressed."},
	"gyazo-api-token":       {Status: VerificationAuditBlocked, Batch: 9, Notes: "Current provider-owned identity endpoint contract is unavailable."},
	"happyscribe-api-key":   {Status: VerificationAuditBlocked, Batch: 9, Notes: "Private transcription listing lacks an authoritative bounded contract."},
	"humanity-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate current-user ID and suppress extensive employee PII."},
	"hybiscus-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate documented quota fields and structured errors."},
	"ibmcloud-user-key":     {Status: VerificationAuditReviewed, Batch: 9, Notes: "IAM token exchange is schema-classified and suppressed."},
	"iconfinder-api-key":    {Status: VerificationAuditReviewed, Batch: 9, Notes: "Bounded iconset collection is schema-classified and suppressed."},
	"insightly-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correlate pod context and preserve daily-quota ambiguity."},
	"interseller-api-key":   {Status: VerificationAuditBlocked, Batch: 9, Notes: "Provider service sunsets on December 15, 2026."},
	"intrinio-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress account identity and usage metadata."},
	"juro-api-key":          {Status: VerificationAuditReviewed, Batch: 9, Notes: "Template collection is schema-classified and suppressed."},
	"knapsackpro-api-token": {Status: VerificationAuditReviewed, Batch: 9, Notes: "Build collection read is schema-classified and suppressed."},
	"kylas-api-key":         {Status: VerificationAuditReviewed, Batch: 9, Notes: "Bounded contact response is schema-classified and suppressed."},
	"leadfeeder-api-key":    {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy account collection is schema-classified and suppressed."},
	"livestorm-api-key":     {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Accept documented empty authentication response and classify statuses."},
	"loadmill-api-key":      {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate current teamLabels schema and documented filters."},
	"loyverse-api-token":    {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress merchant account identity."},
	"lunchmoney-api-token":  {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress current-user and budget identity."},
	"madkudu-api-key":       {Status: VerificationAuditReviewed, Batch: 9, Notes: "Legacy no-workload authentication ping is schema-classified and suppressed."},
	"mailjetsms-api-token":  {Status: VerificationAuditBlocked, Batch: 9, Notes: "Implemented SMS route lacks a current verification contract."},
	"mailsac-api-key":       {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate account identity, suppress quota data, and support current key form."},
	"mavenlink-api-token":   {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace collaborator listing with current-user identity."},
	"meistertask-api-token": {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress current-person identity."},
	"meraki-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace organization listing with administered identity."},
	"mindmeister-api-token": {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace deprecated map listing with v2 current-user identity."},
	"miro-api-token":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Validate and suppress OAuth token context before auth-only promotion."},
	"mixmax-api-key":        {Status: VerificationAuditBlocked, Batch: 9, Notes: "Current bounded identity endpoint contract is undocumented."},
	"moonclerk-api-key":     {Status: VerificationAuditBlocked, Batch: 9, Notes: "Legacy private forms API lacks a current provider contract."},
	"moralis-api-key":       {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe NFT lookup consumes Data API workload."},
	"newscatcher-api-key":   {Status: VerificationAuditReviewed, Batch: 9, Notes: "Known unsafe subscription request consumes API-call allowance."},
	"ngc-api-key":           {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Split legacy, personal, and service key contracts."},
	"nimble-api-key":        {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Correct current-user schema and token boundaries."},
	"nozbeteams-api-token":  {Status: VerificationAuditBlocked, Batch: 9, Notes: "Private user-list contract lacks current provider documentation."},
	"nvapi-key":             {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Establish the undocumented caller-info success schema before promotion."},
	"optimizely-api-key":    {Status: VerificationAuditRequiresHardening, Batch: 9, Notes: "Replace project listing with current-user identity."},
	"overloop-api-key":      {Status: VerificationAuditBlocked, Batch: 9, Notes: "Authoritative bounded identity contract is unavailable."},
}

func buildVerificationAuditReport(ds []Detector) VerificationAuditReport {
	infos := RegistryInfo(ds)
	report := VerificationAuditReport{Total: len(infos), Entries: make([]VerificationAuditEntry, 0, len(infos))}
	for _, info := range infos {
		entry := VerificationAuditEntry{ID: info.ID, Name: info.Name, Verifiable: info.Verifiable, VerificationSafety: info.VerificationSafety}
		assessment, assessed := verificationAuditAssessments[info.ID]
		switch {
		case !info.Verifiable:
			entry.AuditStatus = VerificationAuditNoVerifier
			report.NoVerifier++
		case !assessed:
			if info.VerificationSafety == VerificationSafetyUnreviewed {
				entry.AuditStatus = VerificationAuditPending
				report.PendingReview++
			} else {
				entry.AuditStatus = VerificationAuditReviewed
				report.Reviewed++
			}
		default:
			entry.AuditStatus = assessment.Status
			entry.AuditBatch = assessment.Batch
			entry.Notes = assessment.Notes
			switch assessment.Status {
			case VerificationAuditReviewed:
				if info.VerificationSafety == VerificationSafetyUnreviewed {
					entry.AuditStatus = VerificationAuditPending
					report.PendingReview++
				} else {
					report.Reviewed++
				}
			case VerificationAuditRequiresHardening:
				report.RequiresHardening++
			case VerificationAuditBlocked:
				report.Blocked++
			default:
				report.PendingReview++
			}
		}
		report.Entries = append(report.Entries, entry)
	}
	return report
}
